### ISSUE TITLE
When opening an existing spec, .tla files don't look clickable

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#114]
This occured on MacOS across multiple versions.

1. Create a TLA+ file in an outside editor.
1. In TLA+ toolbox, click Open Spec > Add New Spec.
1. Click "Browse".
1. Navigate to existing TLA+ file.

**Expected Behavior:** Filename should be black, clicking it should highlight in blue.

**Actual Behavior:** Filename is grey and looks unclickable. If clicked, does not highlight. However, it is still selected and, if chosen, will properly load the module. 

This seems to be a UI/UX issue.

![image](https://user-images.githubusercontent.com/2660212/32914779-5dc9a03e-cadc-11e7-9192-c7c473f46713.png)

**Comment by quaeler** [comment]
This is because we're actually displaying what SWT considers a Save dialog for opening because, [according to code comments](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox/src/org/lamport/tla/toolbox/util/UIHelper.java#L669), using an Open dialog doesn't allow for new file creation.

Perhaps this was true for an older version of Eclipse and is no longer true, i'll put it on my plate to try.

**Comment by quaeler** [comment]
Yes, at least in 10.12.6, the cocoa panel presented allows no text input for naming a new file and does not allow an open on a directory; as it is OS X behaviour that a save panel displays existing files grayed out, we will continue to see the above reported behaviour.

It seems like we either mark this issue as 'cannot fix', or we allow the open-selection of a folder and then the user's entry in "Specification name:" text field of the wizard page is used for a filename.

**Comment by lmBored** [comment]
I'm having the same issue now in 2025, TLA+ toolbox 1.7.4 :((

**Comment by lemmy** [comment]
@lmBored You might want to try the [VSCode TLA+ extension](https://marketplace.visualstudio.com/items?itemName=tlaplus.vscode-ide) instead.
