### ISSUE TITLE
Include step names in error trace

### ISSUE THREAD

**Issue by jazzdelightsme** [tlaplus/tlaplus#115]
The error trace is one of the core features of the toolbox. The highlighting of which state changed is great. Thank you!

It's also really great that double-clicking on a step will take me to the corresponding location in the TLA+ spec. But if the step name were included in the error trace, I probably wouldn't even need that double-click functionality very much.

In other words, instead of:

    <Action line 51, col 3 to line 53, col 136 of module CompObjectDestruction>

I'd really much rather see:

    <AcquireLock (module CompObjectDestruction)>

This would let me read through the error trace and quickly understand the steps that were taken, without having to puzzle out the meaning of the changed variables, or repeatedly jump back and forth between the spec and the error trace.

**Comment by lemmy** [comment]
We have to take into account that the error trace can link to a particular disjunct of the action: 

```tla
EXTENDS Integers
VARIABLES x

Init == x = 1

Next == \/ x' = 23
        \/ x' = 42
```

The violation of the invariant x#42 will link to the second disjunct, not to Next.

**Comment by quaeler** [comment]
Until some day that #121 may be implemented, we can walk the syntax tree from the SpecOp (since we have the parsed location) finding the smallest containing SyntaxTreeNode which has a non-null `one` (sigh) and then dump the image of the 0th `zero` element of the STN contained in that `one` and whose image is `N_IdentLHS`.

I'll make it so if this approach doesn't have a recognized flaw.

**Comment by lemmy** [comment]
@quaeler I think I've found a fix that is simpler and also shows the action names as part of the command line output.

**Comment by jazzdelightsme** [comment]
I just tried this out... it's fantastic--thank you!
