### ISSUE TITLE
Make state graph more readable by humans

### ISSUE THREAD

**Issue by jazzdelightsme** [tlaplus/tlaplus#116]
The new state graph feature is cool!

For my particular model, though, I can't really read it. My model has nine variables, the state of which is printed inside each state (49 distinct states in the error case that I am looking at; something more like 110 when fixed). It's very impressive-looking, but I can't use it or show it to anybody.

Some things that might improve it:
  * Inside each state, either show only the variable that changed, or perhaps highlight the one that changed (similar to the error trace view). That would allow me to visually walk through the graph, seeing "in this step, we increased the refcount; in this step, we acquired the lock; etc.".
  * It might also be helpful to label state transitions with step names. I don't know how well that will work visually, but it is how I would ideally be able to read the graph--as I trace my finger through the graph, I can say "the IncrementRefCount step was taken, then the AcquireLock step was taken, etc.". (see also #115)

**Comment by lemmy** [comment]
@jazzdelightsme Do you have the bandwidth to work on this feature if I guide you?

**Comment by jazzdelightsme** [comment]
> Do you have the bandwidth?

Unfortunately, not in the near future. :(

**Comment by lemmy** [comment]
[http://www3.hhu.de/stups/prob/index.php/Main_Page](ProB) has more sophisticated [support to visualize state graphs](http://www3.hhu.de/stups/prob/index.php/State_space_visualization_examples#Alternating_Bit_Protocol) and - fortunately - can model check TLA+ specifications.
I suggest to try out ProB to identify those features that should be included in the TLA+ Toolbox.

**Comment by will62794** [comment]
Hello,

This is a feature that I think would be nice to add to the TLA+ toolbox and I had some time to work on it. I played around with some simple specs and visualized them in the TLA+ toolbox and also in ProB, to see how they compare. I also started working on a POC for showing/highlighting the changed variables in state graph transitions. I used the following simple spec for testing state graph visualization:

```tla
VARIABLE varA, varB
Max == 3

Init == varA = 0 /\ varB = 0

IncA == (varA' = (varA+1) % Max)
IncB == (varB' = (varB+1) % Max)

Next == \/ IncA /\ UNCHANGED varB
        \/ IncB /\ UNCHANGED varA
        \/ IncA /\ IncB
```

Here is an example of how ProB visualizes the state space:

![image](https://user-images.githubusercontent.com/6131840/34903234-42724fec-f7fb-11e7-8d1d-bea444d07393.png)

And how the TLA+ toolbox would with the changes from my POC:

![image](https://user-images.githubusercontent.com/6131840/34903244-5d6a7252-f7fb-11e7-822f-4277f355ba95.png)

My approach isn't perfect, but it's a start. On each edge label you could include the name of TLA+ transition/action but it seemed more difficult to get access to a named action from certain places in the code, so I decided to try displaying just the raw state diffs on each edge label. This very may well get very cluttered very quickly, but for small to medium graphs maybe it would be acceptable. Also, the idea of highlighting the changed state inside a node sort of works, but there is always the issue of having multiple transitions that go to the same state, but update different variables, which makes the highlighting less understandable. For example, for a state `(x=1, y=1)`, there might be one transition coming into that node such that `y=2 /\ y'=1` (the transition only updates y), which would require the variable `y` to be highlighted in the node, because it changed. But if there was another transition `x=2 /\ x'=1` that also came into that node, the variable `x` would also be highlighted. So, in a case like this it becomes harder to visually understand which transitions are changing which variables, just by looking at the highlighting. That is why I thought of adding in the edge labels, which gives you the full information about which variables changed in a transition. This is just a rough outline. You guys can see if you like this general direction.

Also, I had a few quick questions about the codebase that I thought I would mention while posting here.

1. The interface [TLCState.java](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/tool/TLCState.java) in the TLC model checker doesn't seem to provide any clear way to actually retrieve the set of variables and the values of the variables in a state. It seems odd that this interface doesn't expose something like that, unless I am looking in the wrong place. For example, for my POC I added a method to `TLCStateMutSource.java` that returns the current variable values as a `HashMap<UniqueString, Value>`i.e. just a key-value mapping of variable names to their values. Any insight on this would be helpful.

2. [DotStateWriter.java](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/util/DotStateWriter.java) is where I made most of the code changes. I was wondering if there would be an easy way to pass in the "named" action to that code i.e. the `writeState` method. This would allow for labeling edges with action names, like I mentioned above.

Feel free to leave any comments, thoughts. I have been studying and exploring TLA+ in the past year and have found it to be a remarkably elegant and powerful. I am excited to start helping out on the TLA+ tools project! Thanks!

**Comment by lemmy** [comment]
Thanks @will62794 for your efforts. I agree with you that it makes more sense to visualize the difference of two states on the edge rather than the node. Unfortunately, this doesn't scale well unless we provide a more interactive frontend (e.g. support hovering/mouse-over, clickable edges, callouts,....). A GraphViz wiz might be able to help here.

Your addition to TLCState.java sounds fine. Note that I recently added something similar in a patch for issue #118. Passing the action instance to IStateWriter is something we can easily do if needed.

**Comment by will62794** [comment]
Thanks for the response @lemmy. I like the idea of making the graph interactive, to reduce visual clutter. I am going to spend a bit more time thinking about the cleanest way to visualize state transitions that is both clear and also scales well. If we do provide an "interactive graph" option, we can most likely make it optional, so that people can default to the basic state graph if they want.

Since the code changes I made seem generally acceptable to you, I will try to go ahead and put together a full patch, and open a pull request when ready. Thanks!

**Comment by will62794** [comment]
For reference, here is another iteration (visualizing the same spec as above) that includes just action names and names of changed variables on each transition edge. This is more similar to how ProB does it. I think this is a reasonable level of detail to display, since you can determine _how_ any individual variable changed by comparing the two state nodes, but the edge tells you which variables changed and due to what action. This is the spec:

```tla
VARIABLE varA, varB
Max == 3

Init == varA = 0 /\ varB = 0

IncA == (varA' = (varA+1) % Max) /\ UNCHANGED <<varB>>
IncB == (varB' = (varB+1) % Max) /\ UNCHANGED <<varA>>
IncBoth == (varA' = (varA+1) % Max) /\ (varB' = (varB+1) % Max)

Next == \/ IncA
        \/ IncB 
        \/ IncBoth
```

![image](https://user-images.githubusercontent.com/6131840/35080450-9dd6b6be-fbdb-11e7-9df6-17725509688a.png)

It is challenging to make these state diagrams scalable while still providing the right amount of useful information. Adding more advanced interactivity would help with this, but for now, I am trying to limit this to static diagrams that can be produced by Graphviz.

**Comment by will62794** [comment]
Another iteration with an action legend and pushing the changed variables closer to the next state node. Unfortunately, it seems like moving the changed variables made it more cluttered near the node, especially when there are multiple transitions that enter that node. I am wondering if it would come out cleaner if we left the set of changed variables closer to the middle of the transition edge. I can play around with the GraphViz parameters a bit more to see if I can improve this version in terms of node/edge/label spacing. I think the colorized action edges with a legend is a generally a good approach, though. Now I think it's just a matter of how to display the action names and the set of changed variables.

![image](https://user-images.githubusercontent.com/6131840/35131485-64933ddc-fc94-11e7-9b71-04f543877abe.png)

**Comment by lemmy** [comment]
Do we all agree that edge coloring to indicate actions is the way to go? If yes, can you provide a patch that adds support for edge coloring with a legend? I suggest that edges are only labeled with the action name if the number of total nodes is very low.

**Comment by will62794** [comment]
I'll work on the patch. Will also wait and see if @jazzdelightsme has any opinions on this since he was the original poster.

**Comment by jazzdelightsme** [comment]
Sounds good to me.

**Comment by lemmy** [comment]
It just occurred to me that we want to support user-defined filtering of certain (auxiliary) variables. For example _pc_,  _stack_, ... (artifacts of a PlusCal algorithm) which are of little or no relevance to the actual algorithm.

Such filtering could be done at model checking time but I assume dynamically defined filters - applied to the generated graph - are more useful in the long run.

**Comment by will62794** [comment]
Yep, that sounds like a good feature to include. If it doesn't add too much complexity, I can include it in this change; otherwise I might add it in a follow up patch if that's alright with you.  

My patch is mostly ready, excluding a few of the changes to the Toolbox UI that I wanted to run by you first. First, I will mention the changes I made to TLC. Basically, I added optional `-colorize` and `-actionLabels` flags to the TLC command line parameters that only apply if the "dump as dot" parameter is also specified. Each of these parameters can be enabled/disabled independently. I know you mentioned that we could enable the edge labels based on a node count threshold, but it just seems like such a threshold would end up being pretty arbitrary. Providing it as an option to the user seems like a good approach to me. If they test out their graph and see it is too cluttered with labels, they can optionally disable them. The default will still be to exclude any colorizing and labels. 

As far as the Toolbox goes, these TLC parameter changes would imply adding two new checkbox options under the "Visualize state graph" checkbox option. Each new checkbox would be a sub-option and would be something like "Colorize Graph" and "Add Action Labels". If that seems good to you, I will go ahead and make the UI changes and include them when I post this patch.

**Comment by lemmy** [comment]
Lets leave projection for a future iteration once we support interactive visualization such that projection can be changed without re-running TLC.

With regards to the TLC command line parameters, I'd rather suggest to not introduce new flags. Instead make it additional (optional) parameters of dump, e.g. something along the lines of _-dump dot[colorize,actionlabels]_.

UI-wise we generally try not to turn the Toolbox into a [cockpit of a 747](http://i.dailymail.co.uk/i/pix/2017/05/23/12/408BC85C00000578-4530032-Think_your_office_computer_is_complicated_Try_this_for_a_work_sp-a-17_1495537209345.jpg) which is the reason why I want no additional checkboxes and just turn _colorize_ and _actionlabels_ on by default. Another reason to keep the model editor's UI unchanged is that we don't want to change it back once we have this more interactive visualization.

**Comment by will62794** [comment]
@lemmy That all seems fair. I'll update things accordingly.
