### ISSUE TITLE
TLA+ Toolbox should have a REPL

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#124]
From my own experiences with Alloy, a REPL is really nice. It makes learning the language easier, as you don't have to add anything to your core spec to explore. It makes it possible to query information about a given trace to learn more about it. Andrew Helwer [cites a REPL as a key advantage of Runway](https://groups.google.com/forum/#!topic/tlaplus/5Xd8kv288jE). 

This has been discussed [before](https://groups.google.com/forum/#!topic/tlaplus/WdDT5sKY7rI). Here were some alternatives raised:

* _Using "Evaluate Constant Expression":_ This only works on the initial state of a behavior. It takes time to run. It does not (easily) allow defining new operators without using `let`, which is awkward. No history of expressions.
* _Using multiple `ASSUME`:_ Limitations covered by Chris Newcombe [here](https://groups.google.com/d/msg/tlaplus/WdDT5sKY7rI/OcO7FUEtW-kJ).
* _Using Error Traces:_ Evaluated at every step of the trace, cluttery, specifically only for debugging while specs fail.

Lamport asked for [specific scenarios](https://groups.google.com/d/msg/tlaplus/WdDT5sKY7rI/v1feH95tiikJ) for where a REPL would be useful. Here are some I've run into:
* I'm not sure a particular part of the language works. Can I do `CHOOSE x \in A, b \in Y`? With a REPL, I can test that quickly and see it does not work.
* I'm not sure what a particular logical expression does. Is `\E foo \in F: \A bar \in B` what I want? With a REPL, I can try a few different logical expressions and see what I want.
* A spec is failing and I don't understand why. I could use Error Traces, but I don't know what I'm looking for yet. I want be able to take the state one step before the error and try several different expressions to see if I can figure out what it is I don't know.
* I want to use some debugging operators that shouldn't be part of the spec.

I think all of these could be resolved with a REPL that would allow the following:
1. Load at the initial state of a spec, or a given state of a failing behavior
1. Definition of new operators and actions
1. Evaluation of arbitrary expressions, including with the new operators and actions
1. Fast (May be untenable if requires heavy TLC refactors)

To make this simpler, the REPL should **not** be able to change the trace. If `x = 1` and `x' = 2`, `x' = 3` would be `FALSE`. This means that you cannot use the REPL to test a change to a spec. You can only use it to explore information about an existing spec.

**Comment by lemmy** [comment]
ping @will62794 because of https://github.com/will62794/tlaplus_repl

**Comment by will62794** [comment]
I was aware of this Github issue before I created my Python based REPL. I figured that my tool would contain a subset of the functionality that would eventually be desired in a full-fledged TLA+ REPL (one that had more explicit support from TLC and closer integration with the Toolbox). I wanted something to use before this Github issue was completed, so I worked around the existing limitations of TLC. I imagine my tool could serve as a reasonable testing ground for ideas/features that we might want to add in to a full REPL. It could also let people play around with it and see if they find such a tool useful, even if it is a bit primitive.

**Comment by lemmy** [comment]
FWIW a list of related changes/issues:

* Performance of Trace Explorer has been improved e48c1c646050c82faf6bc7adaf2f3cf10f8f0d93
* Model editor can be configured to open ```Evaluate Constant Expressions``` in a dedicated tab #288 
* ```_TEPosition``` & ```_TETrace``` built-in operators for Trace Explorer increase expressiveness
* Interesting/Given states of a behavior can be made the new initial state of a model  #275 
* Trace animation #310

**Comment by will62794** [comment]
@lemmy For personal interest I recently did a bit of experimentation inside TLC to see what it would take to add REPL-like functionality to that code. I made some progress but one issue I am curious about is TLC's ability to evaluate "standalone" TLA+ expressions. It seems that many of the existing classes and interfaces always require a full spec for parsing. For example, the [Tool](https://github.com/tlaplus/tlaplus/blob/eddfc1cbf03984d65df56e9cf7061d7b0df7e426/tlatools/src/tlc2/tool/impl/Tool.java#L111-L113) object. Is the requirement of having a full spec an inherent aspect of how the TLA+ parser is written? If that is true it would seem more difficult to build a REPL that can evaluate basic TLA+ expressions like `{1,2,3} \X {4,5,6}` without constructing and parsing an entire spec. Of course, the workaround by putting a single `ASSUME` statement into an empty spec also works, but doesn't seem ideal. Or, at least, I would hope that eventually that wouldn't be necessary. I am also assuming that changing the parser to handle individual expressions like this would not be an easy (or low risk) task.

There is one specific example where I thought the ability to evaluate single expressions would be useful. Let's say a basic REPL allowed users to input either (1) expressions or (2) definitions. Expressions are just normal TLA+ expressions and definitions are operator definitions with 0 or more arguments e.g. `Var == 3`. For the REPL to know whether an input is an expression or a definition, it would need to parse the input. But you can't do this directly if you can only parse a full spec. And I'm not sure what you could put into a full spec to be parsed in this case. If the user inputs a definition then you don't want to wrap it in an `ASSUME` statement (i.e. `ASSUME x == 5`), but if it's an expression then you do want it to be wrapped in `ASSUME`. Maybe there are clever ways to get around these kinds of issues but this is just one example of a problem that I felt would be made much simpler if it were possible to parse individual TLA+ expressions. Would be interested to hear your thoughts.

**Comment by lemmy** [comment]
@will62794 I believe everybody agrees that support for parsing fragments of a specification would be useful (to e.g. also build an incremental compiler).  The efforts to build such a feature however are considered too high which is why nobody has deeply looked into it.

As a workaround, we could consider pushing the workaround of creating an "ASSUME spec" into TLC so that from the REPL's perspective, it would appear as if single expressions can be evaluated.  However, the error reports for when such an expression fails to evaluate would be messy.

At any rate, I feel we should talk about this in more detail.  Would you be available for a Skype call next week?

**Comment by lemmy** [comment]
Related because of in-memory FS: https://github.com/tlaplus/tlaplus/issues/378

**Comment by lemmy** [comment]
Can't do due to lack of resources. Please reopen if somebody wants to work on it.

**Comment by will62794** [comment]
@lemmy After thinking on this a bit more, I have come to the conclusion that building a REPL into TLC may be potentially less valuable than improving TLC so that REPL like tooling can be built more easily around it. Designing a REPL interface that pleases everyone's needs and provides a satisfactory set of features also seems harder to get right, since different people may have different views on what a REPL should look like and what features it should provide. 

Instead of adding a built-in REPL to TLC, my thinking was to add a feature to allow TLC to do all the things it can currently do, but without paying the startup/warmup time of the JVM. In an ideal world, I could imagine that TLC has an "advanced server" mode, where it listens on a socket and clients could interact with it over HTTP or some similar protocol to provide better monitoring, control, etc. Designing the format of such a protocol, though, seems a much bigger task and not one I want to invest time into now. So, as a simpler approach, my thought is to have a kind of "minimal server" mode for TLC that provides exactly the same command line interface as TLC currently does, but it allows you to avoid paying the upfront JVM startup costs by running the TLC process continuously and accepting input via stdin. The goals are to (1) allow execution of any normal TLC invocation without paying JVM startup cost and (2) keep the interface of the invocation the same (i.e.textual command line arguments). 

For example, you might currently run the following command to check a model:

```
java tlc2.TLC -config inchworms.cfg inchworms.tla
```

In the new "server" mode, though, you would instead run TLC first with a command like:

```
java tlc2.TLC -server
```

which would start up the Java process, and then you send the same command line arguments you would pass normally to the running process via stdin (terminated by a newline) i.e.

```
-config inchworms.cfg inchworms.tla
```

TLC would then run as it would normally until it completes or returns an error, and then it goes back to listening on stdin for new inputs. The output can simply be piped to a file that is continuously written to. It's essentially a crude server with an extremely simple RPC mechanism i.e. it receives textual commands on stdin and the output goes to stdout.

To give a sense of how much this can improve TLC execution latency, I prototyped the idea and did some tests. With the existing version of TLC, on my 2015 Macbook with Java 11.0.2, it seems to take around 1.5 seconds on average to parse and check a spec that contains only ASSUME statements. If I run under my prototype "server" mode, and run the same model 5 times in a row (while the same TLC Java process is running continuously), I get durations of 866ms, 223ms, 170ms, and 166ms, 137ms. The first execution might be slower if some parts of the JVM aren't warmed up. Not sure about the details there, but latencies of around 150ms are very much in a reasonable range for interactive REPL like tooling.

One of the important benefits to this approach over a standard built in REPL for TLC is that it can hopefully provide a generic way for many different tools to execute TLC operations with low latency. For example, the [TLA+ VS Code extension](https://github.com/alygin/vscode-tlaplus) already has a feature to evaluate a given constant expression on demand, which is like a pseudo REPL. It uses the ASSUME construct trick, though, and starts up a new JVM each time, so it suffers from the same latency issues as https://github.com/will62794/tlaplus_repl. If we implemented a built in TLC REPL, the VS Code evaluate expression feature wouldn't automatically benefit from it. If we take this approach, however, then the interface to TLC remains almost identical, but latency can be improved over 10x for fast running models. Similarly, now that we have the ability to do trace exploration from the command line (#393), we might want to have external tools that can do low latency trace exploration. Trace animation is one example, as well as the planned support for exploration in the VS Code extension. The Toolbox itself could theoretically take advantage of this feature as well to make model startup times faster, perhaps with some minor refactoring.

I feel this is a reasonable direction and will be relatively simple to implement. I have a working prototype that I may get more time to work on and submit for review in the coming weeks. I just wanted to lay out my thoughts on this, especially if anyone else with interest in this feature might want to weigh in. From a broader perspective, I feel that it is generally a good philosophy to improve TLC in ways that make it more amenable for others building their own tooling around it, since everyone has their own tastes and use cases. Tools like

- https://github.com/alygin/vscode-tlaplus
- https://github.com/will62794/tlaplus_repl
- https://github.com/kelvich/tlaplus_jupyter
- https://github.com/hwayne/tlacli 

etc., are good examples of this.

**Comment by lemmy** [comment]
Simon Zambrowski spent quality time in an attempt to make TLC support checking different specs with a single VM instance--he gave up eventually.  In order to minimize TLC's startup time, [GraalVM native image](https://www.graalvm.org/docs/reference-manual/native-image/) could be the solution.  I toyed with GraalVM and TLC a couple of months ago and it basically worked.

**Comment by pron** [comment]
@lemmy Native Image is a great way to reduce startup of applications with complex setup to the sub-millisecond range. It does, however, increase build times, and sub-millisecond startup is often not needed, and VM startup in JDK 14/15 is already below 40 ms. So while Native Image could help, I would recommend first trying less extreme measures, such as AppCDS.

**Comment by lemmy** [comment]
If we find that sub-millisecond startup time is a must have for a REPL, increasing TLC's build time shouldn't be an issue.

**Comment by pron** [comment]
It actually helps for more than just sub-millisecond startup. It's possible that there is some slow TLC-specific initialization that could be made *much* faster with Native Image. My point is just that Native Image is very powerful, it certainly has some very good uses -- quite possibly here, too -- but it should be used as after easier startup time solutions are exhausted, as it also carries some costs (beyond just build time, which is considerable) -- it has some limitations on what code can be compiled, it has to be configured specifically. So it shouldn't be the *first* thing to try, but it is certainly a powerful option to consider.

**Comment by will62794** [comment]
I don't think that JVM startup time is the bottleneck, and we definitely don't need sub millisecond startup times. I would need to do more measurements to verify but from some basic profiling it seems that SANY parsing and semantic analysis takes up a large portion of the time needed to process a simple spec. GraalVM definitely sounds cool, but it also feels like a pretty big hammer for a small nail. I know little about it, but I would imagine it brings along a host of other potential complexities, as @pron  alluded to. I would imagine there are cross platform compatibility issues as well to consider when using the native image feature. 

@lemmy Do you have opinions on the notion of a lightweight server mode for TLC? In my prototype I listen on a socket at the beginning of TLC execution and basically run [this code](https://github.com/tlaplus/tlaplus/blob/a8fc5b1bf6dfb29679848fdd6f15f3c3ada9efa2/tlatools/org.lamport.tlatools/src/tlc2/TLC.java#L242-L289) in a loop, re-running on the receipt of new command arguments over the socket. On the first execution the duration of the main [`tlc.process()`](https://github.com/tlaplus/tlaplus/blob/a8fc5b1bf6dfb29679848fdd6f15f3c3ada9efa2/tlatools/org.lamport.tlatools/src/tlc2/TLC.java#L289) call is around 700ms but eventually drops down to around 100-200ms after ~10 executions of this simple spec i.e. `java tlc2.TLC tlarepl`:

```tla
------------------------- MODULE tlarepl -------------------------
EXTENDS Naturals,Reals,Sequences,Bags,FiniteSets,TLC
ASSUME PrintT({1,2,3} \X {4,5,6})
replvalue == 5+6
=============================================================================
```

These are the actual durations:

```
Duration time: 712ms
Duration time: 217ms
Duration time: 164ms
Duration time: 186ms
Duration time: 198ms
Duration time: 175ms
Duration time: 131ms
Duration time: 113ms
Duration time: 114ms
Duration time: 123ms
Duration time: 112ms
Duration time: 109ms
Duration time: 112ms
Duration time: 88ms
```

Do you think this can be explained by some kind of JVM "warmup" effects? A latency within this range is OK for a REPL, I think. Ideally, REPL latency would be mostly imperceptible by a human user, which seems to be in the [10s of milliseconds range](https://www.pubnub.com/blog/how-fast-is-realtime-human-perception-and-technology/). If parsing is the bottleneck, though, we might not be able to achieve that without future parsing optimizations.

**Comment by lemmy** [comment]
It seems as if the most important message in https://github.com/tlaplus/tlaplus/issues/124#issuecomment-626455175 has been lost in discussions about technical features and latency:  TLC has to be freshly initialized for every spec.  Otherwise, TLC produces bogus results because statically initialized code does not get properly reset.  IIRC, @quaeler recently ran into this problem and hopefully can share some details (a test case?).  This is the bug that Simon tried to fix but gave up after a couple of weeks.

The easiest workarounds is to simply launch a new JVM, which has been done in case of the Toolbox to evaluate constant and trace expressions.  Alternatively, one can somehow reload *all* classes by e.g. fiddling with classloaders ([OSGi](https://github.com/lemmy/tlaplus/tree/mku-osgi), custom [classloader](https://github.com/tlaplus/tlaplus/blob/ab14a33e39c78e4c88e81b664b9a8c916b943cab/tlatools/org.lamport.tlatools/test/util/IsolatedTestCaseRunner.java)).

**Comment by quaeler** [comment]
Yes - i wrote this class to use as a workaround - https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tlc2/TLCRunner.java

**Comment by will62794** [comment]
Sorry for not acknowledging it directly @lemmy, but I did see your [comment](https://github.com/tlaplus/tlaplus/issues/124#issuecomment-626455175) above about Simon Zambrowski's failed attempts to check multiple specs in the same JVM. In my limited testing, I have not seemed to face issues with this, but I don't doubt that it's a real issue. I will keep it in my mind if I start working on this in more depth. Maybe I haven't been encountering the issue since I haven't actually been model checking my specs i.e. I am only parsing and checking ASSUME statements. I might do more investigation on it if it becomes a problem in my ultimate implementation.

On a side note, I was curious about examining the performance of TLC startup and spec parsing a bit more. I tried to profile the execution of the simple spec I posted near the beginning of JVM startup and after it was running for a while to understand some of the potential warmup effects that might be at play here. I used [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) for this. I took two profiles: the first is of the execution of a spec the first time after TLC started up and is waiting on a socket to receive commands, the second is of the execution of a spec after I re-ran the spec around 20 times or so, to see if that would warm up the JVM at all. The flamegraphs of these profiles are linked below:

[prewarm.svg](https://www.dropbox.com/s/cz902mr82xmfmgf/profile_prewarm.svg?dl=0)
[postwarm.svg](https://www.dropbox.com/s/tt968mmhzxpdols/profile_postwarm.svg?dl=0)

It does seem that the contribution of the `CompileBroker::compiler_thread_loop()` to the overall sample count becomes smaller in the post warm graph (down to around 36.67% from 59.41%), which seems to indicate some improvement due to JVM warmup over time. These results appear roughly similar to those [mentioned](http://www.brendangregg.com/blog/2016-09-28/java-warmup.html) by Brendan Gregg when analyzing JVM warmup. I am speaking with fairly limited knowledge of the JVM internals, so my analysis could be off base, but it at least gave me some starting point to see what contributes to TLC performance when parsing/checking specs. It's also interesting for me to understand the perf profile of the work SANY has to do. This profiling work isn't entirely relevant to the REPL implementation changes, but it's just some auxiliary investigation I did that I figured I would post here. 

I also had another thought when looking at parsing a bit more in TLC and comparing it to the [PlusPy](https://github.com/tlaplus/PlusPy) tool. In my [REPL POC](https://pluspyrepl.williamschultz.repl.run/) that uses PlusPy as parser and interpreter, I measured the time it takes to evaluate simple TLA+ statements. Often, the duration is under 10ms, and for very simple statements, under 5ms. My intuition tells me there's something off here if SANY takes on the order of 100ms (even without JVM startup time) to parse and evaluate statements from a similarly simple spec. After it's been properly warmed up, I would expect a modern JVM to outperform Python by a considerable amount (at least an order of magnitude?). And yet, it seems like PlusPy is doing essentially the same work in a fraction of the time. Would you agree with this intuition? It just seems like there's some factor I'm missing or else SANY is a really slow at parsing. Would be curious to hear if you had any thoughts on this.

**Comment by lemmy** [comment]
@will62794 What do the numbers look like when you parse a large spec such as [farsite](https://github.com/tlaplus/tlaplus/tree/master/toolbox/org.lamport.tla.toolbox.uitest/farsite)?  Keep in mind that it was never an objective to make SANY fast (parsing farsite completes in reasonable time). Also, PlusPy parse only a subset of TLA+ (no proofs) and misses other features such as definition overrides.

When it comes to the execution of TLA+ specs with [PlusPy](https://github.com/tlaplus/PlusPy/blob/master/modules/other/BlockingQueueSplit.tla) or [TLC](https://github.com/lemmy/BlockingQueue/tree/ExperimentalExecutor) - an area where we worked hard to make TLC fast -  my ad-hoc measurements for 3,000,000 operations were:

Native Java app
---------------
real	0m21,638s
user	0m9,027s
sys	0m13,922s

real	0m13,578s
user	0m7,522s
sys	0m10,419s

real	0m14,200s
user	0m8,200s
sys	0m10,714s

TLC-based interpreter
---------------------
real	0m57,537s
user	1m1,879s
sys	0m23,054s

real	1m9,009s
user	1m12,023s
sys	0m24,776s

real	1m9,119s
user	1m13,284s
sys	0m26,188s

PlusPy interpreter
------------------
real	16m46,205s
user	17m0,120s
sys	0m19,939s

Anyway, I suggest to spend too much time on latency/performance for now.  Let's find out what a REPL is good for. :-)

**Comment by will62794** [comment]
Alright, here's a crude demo ([screencast](https://www.dropbox.com/s/1jftr96ljhtnsr5/tlarepl1080.mov?dl=0)). My initial thought is that you can run TLC `-repl` mode with or without a specified TLA+ module file. Without any specified module, you evaluate expressions in an empty context. If you provide a spec, then you evaluate expressions in the context of the spec i.e. as if you had loaded it into the REPL. 

From some quick [searching](https://stackoverflow.com/questions/572001/detecting-and-acting-on-keyboard-direction-keys-in-java), it seems it's not so trivial to build nice console based apps for Java that properly handle arrow key input, etc, so that could make building a nice REPL interface more of a pain. This is a prototype, at least. Nice error reporting is also something that will probably take a bit more time, but probably wouldn't be necessary for a basic initial REPL.

**Comment by lemmy** [comment]
Have you checked out how [jshell](https://en.wikipedia.org/wiki/JShell) has been [implemented](https://openjdk.java.net/jeps/222)?  I assume some improvements have been made since 2009.  I would also suggest to create a new class`tlc2.Repl` with its own main, instead of adding a new flag to (spaghetti) `tlc2.TLC`.

**Comment by will62794** [comment]
Ah, that's a good point about jshell. I'll take a look at that. And I'll make a note of putting the REPL in its own class, once I have a more complete implementation.

**Comment by lemmy** [comment]
FWIW: A short-lived, per-invocation REPL rather than a long-running server would benefit other work such as https://github.com/kelvich/tlaplus_jupyter.

**Comment by lemmy** [comment]
@will62794 Your REPL works nicely.  Do you plan to add features such as syntax highlighting and multi-line comments (the latter would make LET/IN expressions more comfortable to read)?

**Comment by will62794** [comment]
@lemmy Thanks, and thanks for fixing that [dependency problem](https://github.com/tlaplus/tlaplus/commit/f8f057f3e019026e478369c2b82e20677c920335) I missed. 

It would definitely be nice to add some of the features you describe. The REPL is barebones right now but hopefully a good foundation to start from. I might be able to work on more features when I have some extra time. We could consider closing this issue and opening those improvements as separate issues, if you think that makes sense.

**Comment by lemmy** [comment]
Long-term feature/goal: Merge functionality with command-line trace exploration.

**Comment by lemmy** [comment]
@will62794 Do you want to prepare a short screencast that can be shared on the web and linked from the changelog?

(I have no preference WRT creating separate issues).

**Comment by will62794** [comment]
Would [this](https://asciinema.org/a/3lsDwbmVG0iyZHJ3RbhNycQS0) suffice? It's a very basic demo.

**Comment by lemmy** [comment]
Can you create one with more complex expressions such as `LET/IN` with INSTANCE SomeModule?

**Comment by will62794** [comment]
I didn't really consider the ability to do module instantiation in the REPL as a "feature", since it would be pretty awkward to use in practice (you'd have to figure out the location of the temp directory), so I'd rather leave it unadvertised.

**Comment by lemmy** [comment]
Modules in $CWD are resolved by default: https://asciinema.org/a/GO1eKSS33peenZZfqCi2BEwVe

Btw. it would be nice if the repl would read expressions from stdin and print the result to stdout: `tlcrepl 42 = 32`

**Comment by will62794** [comment]
Oh, cool! I didn't realize that.

**Comment by lemmy** [comment]
Additionally, you can set `java -DTLA-Library=/path/to/libraries ...`

**Comment by lemmy** [comment]
To communicate progress, let's close this issue (and eventually create new ones for follow-up work).

**Comment by lemmy** [comment]
The REPL could be optimized by writing a dedicated `SpecProcessor` that does *not* eagerly evaluate expressions.  The current implementation of the REPL evaluates the expressions twice.
