### ISSUE TITLE
TLC produces long stack traces in certain cases if invariant has bug in initial state

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#132]
Setup:

```
EXTENDS Naturals
VARIABLES a, b
vars == <<a, b>>
Init == 
  /\ a \in [1..2 -> 1..3]
  /\ b = TRUE

Spec == Init /\ [][UNCHANGED vars]_vars
```

Set `a >= 0` as an invariant for TLC.

**Expected:** TLC should throw an error, and the error trace should be 4 lines (ending with `a >= 0`).

**Actual:** TLC throws an error, and the error trace is 18 lines (`a >= 0` is still line 4).

**Notes:** The bug only appears with more than one variable. The bug will not appear if any of the following changes are made:

* Removing `b` as a variable
* Changing the order of `a =` and `b =` clauses
* Replacing the invariant with an `a >= 0` clause in the spec itself.

Replacing the invariant with `a = <<9, 9>>` (something that type checks) will list every starting state that fails the invariant. This is **not** order dependent, unlike the error trace issue.

**Comment by lemmy** [comment]
@inieves Any idea what is going on here?

**Comment by inieves** [comment]
@hwayne Can you post the actual error output (all 18 lines) as well as the expected error output (just 4 lines)?

**Comment by inieves** [comment]
@lemmy There might be more than one issue going on here:

1) After some research and discovering the comment at ModelChecker.java@1031, it is clear that an initial state is checked for violation of invariants _only_after_ that particular initial state has been successfully computed... and therefore only after that initial state's CallStack would be useful.  I am saying that if TLC finds that an invariant is violated, it is too late (and therefore meaningless) to look at the CallStack (it should be empty to indicate successful evaluation).  So the fact that the code above outputs a stack trace of 4 lines or 18 lines makes no good sense.  There should only be 1 line of error output and that line should be the location of the failed invariant.  ModelChecker.java@1068 is where TLC notices an invariant violation and throws an exception.  Unfortunately, the exception is caught upstream and TLC assumes (incorrectly) that if an error occurs during calculation of initial states, then the user should be shown a CallStack trace.  The fix to this might be to catch the thrown InvariantViolatedException and to handle it at ModelChecker.java:171 by outputting the location in source of the failed invariant (and not to display CallStack).

2) In this particular example, even though the user should not have seen a CallStack trace, it is worrisome to me that the CallStack was not empty.  Because there were no failures in the calculation of the initial states, the CallStack _should_ have been empty.  That signals to me that there is some other fundamental issue... pops and pushes are not being matched up correctly.  With some basic debug message output on pops and pushes, it should be possible to figure out where the mismatch is occurring.

3) A similar potential mistake in output can occur during computation of successor states.  Here again, if an invariant is violated, the user will be shown a CallStack trace.  The area of interest is ModelChecker.java:259  Unfortunately in this case, there seems to be no InvariantViolatedException
 thrown, so that would need to be added to help detect the unique type of failure.

**Comment by inieves** [comment]
@lemmy I believe I have an idea what the problem is.

After TLC realizes that init has failed, TLC attempts to replay the failure with the CallStack enabled.  In this particular case, the failure happens immediately: the first init state is generated, and then that init state is checked against invariants, and the check fails (basically because of type mismatch).  At this point in time, the CallStack is correct.

However, the failure does not stop progress.  The failure is simply recorded, and init states continue to be generated.  The further generation of init states causes further mutations to the CallStack.

Only after all init states have been generated (ModelChecker@341) does TLC decide to check for violations and then propagate exceptions upstream (ModelChecker@347-354).  However, by this time the CallStack is mutated (from all init state generation after the first init state was generated) and does not represent the CallStack at the time the original exception occurred.

A reasonable solution I can propose would be to add a snapshot of the CallStack to the DoInitFunctor in ModelChecker.  DoInitFunctor already has errState and e which are used to record some state at the time of a violation.  If callStackSnapShot (or something like that) is added to DoInitFunctor, then when the final exception is propagated and a CallStack must be output, rather than outputting the current CallStack (which is mutated and does not describe the exception) the call stack snapshot could be used instead (which is not mutated and does describe the exception).

**Comment by inieves** [comment]
@lemmy Sorry for the delay in response here.
From my research, the fact that Line 8 (b = TRUE) is still on the call stack is not a bug.  

At init time and the call stack will include all the values in a conjunction, not only the value that causes invariant failure.  This has to do with the fact that invariants are checked after a state is computed, not while the state is being computed.

**Comment by lemmy** [comment]
@inieves Thanks for the info.  Can you think of anything that can be done to filter non-relevant elements from the call stack?

**Comment by lemmy** [comment]
@hwayne For correctness reasons, I allowed myself to change "error trace" to "error stack" in your initial comment.  In TLA+ speak an _error trace_ is a prefix of a behavior.  The _error stack_ concerns the evaluation of expressions as part of the initial and next-state predicates.
