### ISSUE TITLE
Support launching TLC from Toolbox's .launch file

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#140]
Historically TLC reads its configuration from a file (commonly called MC.cfg/MC.tla) provided via its "-config" command line parameter. [Configuration](../blob/master/tlatools/src/tlc2/tool/ModelConfig.java) that appears inside a .cfg file is a small set of keywords with which TLC knows which invariants and properties should be checked on a spec. However, a .cfg file does not contain runtime parameters such as number of TLC workers, memory allocated to the fingerprint set... Runtime parameters are passed as [additional command line parameters](../blob/master/tlatools/src/tlc2/TLC.java) to TLC.

The advent of the Toolbox some years ago brought us .launch files. Technically a .launch is an internal Toolbox concept ([actually Eclipse](https://github.com/eclipse/eclipse.platform.debug/blob/master/org.eclipse.debug.core/core/org/eclipse/debug/core/ILaunchConfiguration.java)) which is hidden from Toolbox or TLC users. A .launch file is the persistent storage for all the configuration visualized by the Toolbox's model editor. Thus, the configuration stored in a .launch file is a superset of the .cfg file. A .launch file contains all configuration found in a .cfg, additional TLA+ statements (such as state constraints, invariants, properties) but also TLC runtime parameters.

When the Toolbox launches TLC, it [generates](../blob/master/org.lamport.tla.toolbox.tool.tlc/src/org/lamport/tla/toolbox/tool/tlc/model/ModelWriter.java) the MC.cfg and an MC.tla file. The MC.cfg file contains the configuration discussed above, the MC.tla contains the additional TLA+ statements. The runtime parameters stored in the .launch file are passed to the newly spawned TLC process as command line parameters.

User stories from the engineering realm indicate, that it is difficult to store TLC configuration inside SCM systems such as git. [Some users keep MC.cfg/MC.tla](http://ieeexplore.ieee.org/document/8109276/) while [others keep the .launch file](https://github.com/elastic/elasticsearch-formal-models#how-to-editrun-tla). The former lose the ability to run the spec from the Toolbox and also need to somehow keep the runtime parameters (likely within scripts). The latter has to re-generate the MC.cfg and MC.tla via the Toolbox and manually keep the files in-sync if they wish to run TLC from the command line and Toolbox. The runtime configuration They likely copy&paste from the .launch file to the console/command prompt from where they run TLC.

In order to simplify the scenarios described above, .launch file support should be added to TLC. In other words, it should be possible to run TLC from a .launch file directly.

Technically, this enhancement does not seem difficult. Commit 7e3326aafa54998711990ebbb55d6d879b3acaae already encapsulates Toolbox code to generate the MC.cfg and MC.tla file. The next step is to push the [ModelWriter](../blob/master/org.lamport.tla.toolbox.tool.tlc/src/org/lamport/tla/toolbox/tool/tlc/model/ModelWriter.java) into TLC and call it from TLC's [main method](../blob/master/tlatools/src/tlc2/TLC.java) to generate MC.cfg/MC.tla on-the-fly either into a temporary directory or into in-memory file system. The runtime parameters can be extracted from the .launch file in TLC.java right away.

For the moment, we will ignore the runtime parameters only relevant to distributed and cloud TLC.

There is a chicken or the egg dilemma though. The .launch files contains JVM parameters such as heap space, max stack depth, ... which have to be set on the JVM before launch. If TLC itself is to read the .launch files, it is too late to apply those parameters. What seems possible is to add another IApplication  or extend the [Clouds TLC](https://github.com/tlaplus/tlaplus/tree/master/org.lamport.tla.toolbox.jclouds) app to the Toolbox which essentially acts as a headless variant of the Run Model action.

**Comment by edahlgren** [comment]
I spent a bit of time looking into this and considering the different options. Here's my take, FWIW:

- Today TLC doesn't depend on eclipse libraries. This is a good thing. Practically speaking, users on unusual platforms (e.g. FreeBSD) can easily build TLC. Philosophically, if we believe in the "Unix Philosophy" of "Make each program do one thing well", TLC should remain blissfully unaware of the idiosyncrasies of its clients.

- In theory, TLC could take a .launch file as an argument, build up a set of command line args, and launch a child JVM process that actually executes TLC again with different parameters. I don't think this is the right thing to do however. We would be forced to either ignore the JVM args passed to TLC on the command line in favor of those in the .launch file or merge the args in a way that is likely to confuse users. This goes back to the "Unix Philosophy", if we believe in it: the interface to TLC should be minimal, simple, and well defined.

Some thoughts on other options:

- It seems to me that the absolute simplest way to solve this problem would be to write a very simple, standalone tool that takes a .launch file and emits a string containing a portion of the TLC command line. A user would do something like this:
```
$   /path/to/java -cp /path/to/tla2tools.jar `launch2args /path/to/model.launch`
```
Which would expand to something like:
```
$ /path/to/java -cp /path/to/tla2tools.jar tlc2.TLC -Djava.rmi.foo=bar -deadlock -simulate -config /path/to/MC.cfg /path/to/root.tla
```
This is a nice approach because users can see exactly how TLC is being configured by running launch2args on their .launch files. A user can also easily debug and experiment with TLC on the command line this way. The output of launch2args can be stored in a version control system and be reused as follows:
```
$ launch2args /path/to/model.launch > args.txt
(commit args.txt to version control)
$ /path/to/java -cp /path/to/tla2tools.jar `cat args.txt`
```
It's very easy to execute TLC like this on a Unix system (as shown above). Would it be difficult to do the same on a Windows system?

- The obvious alternative would be what @lemmy suggests, which is to give Toolbox users the option to run the Toolbox in a headless mode. This is nice in the sense that only one tooling component (the Toolbox) needs to know about .launch files. At the same time, users may prefer something like launch2args to avoid building and running the Toolbox when they only need to execute TLC.

Thoughts?

**Comment by lemmy** [comment]
@edahlgren Sounds as if we are moving in the right direction. 

I fully agree that TLC should not depend on Eclipse code. While we already bake a few external dependencies into tla2tools.jar, there is no need here (ModelWriter can be pushed down into tlatools and changed to work without Eclipse classes).

I assume you want to make launch2args part of tla2tools.jar?
```
export CLASSPATH=/path/to/tla2tools.jar
/path/to/java tlc2.TLC $(/path/to/java tlc2.Launch2Arg /path/to/model.launch)
```

Eventually, we might find a way to merge launch2arg into regular TLC without spawning a nested VM.

**Comment by edahlgren** [comment]
> I assume you want to make launch2args part of tla2tools.jar?

Yes, I think it would be easiest for users to depend on a single tla2tools.jar.

> While we already bake a few external dependencies into tla2tools.jar, there is no need here.

As long as we're fine with using standard Java XML libraries instead of Eclipse's org.eclipse.debug.core.ILaunchConfiguration to parse .launch files, then yes, I think you're right.

> Eventually, we might find a way to merge launch2arg into regular TLC without spawning a nested VM.

The JVM doesn't support something like OS-level exec (man exec), does it? If I'm right, then basically what you want is a wrapper script around launch2arg and TLC that does support OS-level exec (e.g. bash script, C program), so you can replace the program that parses the .launch file with a JVM instance. That'd work for Linux/Max/Unixes, but I don't know how it would work for Windows.

It might be more productive to think about different types of TLC launchers (things that can execute a pool of TLC instances, for example) instead of trying to shimmy two JVMs together.

**Comment by lemmy** [comment]
> As long as we're fine with using standard Java XML libraries instead of Eclipse's org.eclipse.debug.core.ILaunchConfiguration to parse .launch files, then yes, I think you're right.

The JVM should have everything needed to parse the XML backend file. No new third party dependencies needed.

> > Eventually, we might find a way to merge launch2arg into regular TLC without spawning a nested VM.
> 
> The JVM doesn't support something like OS-level exec (man exec), does it? If I'm right, then basically what you want is a wrapper script around launch2arg and TLC that does support OS-level exec (e.g. bash script, C program), so you can replace the program that parses the .launch file with a JVM instance. That'd work for Linux/Max/Unixes, but I don't know how it would work for Windows.
> 
> It might be more productive to think about different types of TLC launchers (things that can execute a pool of TLC instances, for example) instead of trying to shimmy two JVMs together.

I suggest we keep wrapper scripts and launchers for later as they can be added on top if needed.

**Comment by edahlgren** [comment]
> The JVM should have everything needed to parse the XML backend file. No new third party dependencies needed.

Cool.

> I suggest we keep wrapper scripts and launchers for later as both can be added on top if needed.

Agreed.

**Comment by lemmy** [comment]
Obsolete
