### ISSUE TITLE
Error-Trace Exploration can't resolve definitions in other modules

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#154]
Bug repro steps:

1. Open below specs in the TLA Toolbox (tested in version 1.5.6 on Windows 10 64-bit)
2. Create a model for the SystemMC spec
3. Define MaxCounterValue as 5 (or any number you want), ensure deadlock is being checked
4. Run TLC
5. When deadlock is reached, open the Error-Trace Exploration window
6. Add some expression to check (for example, MaxCounterValue)
7. Click "Explore"; the following error box pops up, unable to find the definition of Null:

![image](https://user-images.githubusercontent.com/718765/38384047-f921d1ce-38c2-11e8-9634-66b1b1a8c87c.png)

```
------------------------------- MODULE System -------------------------------

EXTENDS
    Naturals

VARIABLES
    Counter

-----------------------------------------------------------------------------

Null == CHOOSE n : n \notin Nat

TypeInvariant ==
    /\ Counter \in Nat \cup {Null}

Init ==
    /\ Counter = Null

FirstIncrement ==
    /\ Counter = Null
    /\ Counter' = 0

Increment ==
    /\ Counter /= Null
    /\ Counter' = Counter + 1

Next ==
    \/ FirstIncrement
    \/ Increment

=============================================================================
```
```
------------------------------ MODULE SystemMC ------------------------------

EXTENDS
    Naturals

CONSTANTS
    MaxCounterValue

VARIABLES
    Counter

ASSUME MaxCounterValue \in Nat

-----------------------------------------------------------------------------

S == INSTANCE System

TypeInvariant ==
    /\ S!TypeInvariant

Init ==
    /\ S!Init

Next ==
    IF Counter = S!Null
    THEN S!Next
    ELSE
        /\ Counter < MaxCounterValue
        /\ S!Next

=============================================================================
```

**Comment by lemmy** [comment]
@nikshinde1996

**Comment by fuzz-ai** [comment]
Is there a suggested workaround for this problem?

My best guess is to temporarily add
Null == S!Null
to the top-level module, which worked on a similar example I ran into.

(When this error is encountered on a nontrivial example, the syntax error box can be too tall to fit on the screen.)

**Comment by lemmy** [comment]
@quaeler Can you take a look at the UI layout of the syntax error box?

**Comment by lemmy** [comment]
The underlying bug doesn't appear to have a straight forward fix.

Another variant is:
- Change System's EXTENDS from Naturals to Integers
- Init Counter with -1 instead of Null (change FirstIncrement correspondling)

TE fails because with rather cryptic error about "-" (minus) being undefined.  For this it might suffice to extend the transitive dependencies of System in TE.

**Comment by lemmy** [comment]
LL: The fix is to find all definitions overrides that replace a definition of an operator X in a non-root module with a model value.  For each such X that is not defined or declared in the current spec, a constant X should be declared in TE.tla and overridden by the model value X in TE.cfg.  It's not clear what should be done if X is defined or declared in the current spec.  It's certainly OK if that definition is the same definition of X that was overridden, which was imported into the current spec without renaming.  It's probably also OK if the definition of X in the current spec is also overridden by the model value X.  It's certainly an error that should be reported if X in the current spec is declared to be an operator that takes one or more arguments.  In other cases, it's probably also an error and should be reported by a message like:

       The model value X substituted for X in module Y conflicts with the definition or
       declaration of X in the specification.

**Comment by lemmy** [comment]
Related, I might be useful (e.g. in the scope of https://github.com/tlaplus/CommunityModules) to be able to extend additional modules for trace expressions.

**Comment by lemmy** [comment]
@ahelwer Can you check how this is handled by SpecTE?

**Comment by ahelwer** [comment]
@lemmy I checked and can confirm that ALIAS-style trace expressions work perfectly when using definitions from other modules.

**Comment by lemmy** [comment]
Closing because `ALIAS` doesn't have this problem, and `ALIAS` is where trace expressions evaluation is moving to anyway.
