### ISSUE TITLE
ASSUME statements are not checked in imported modules

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#156]
TLC does not check the ASSUME statement in the System module when model-checking the SystemMC module.

```tla
------------------------------- MODULE System -------------------------------

CONSTANT Input

ASSUME Input = 0

=============================================================================
```
```tla
------------------------------ MODULE SystemMC ------------------------------

S == INSTANCE System WITH Input <- 1

=============================================================================
```

**Comment by lemmy** [comment]
"We expect the assumption to be satisfied when the module is instantiated, but we do not make this a formal requirement." http://lamport.azurewebsites.net/tla/newmodule.html#Section6

**Comment by ahelwer** [comment]
More of a feature request, then!

**Comment by Calvin-L** [comment]
I was recently surprised by this behavior. Since it doesn't look like this behavior will change, here is a lightweight technique I use to address it:

1. Every spec should include an `Assumptions` operator.
2. If A instantiates B, then A should include `B!Assumptions` in its own assumptions.

To use the example in this issue:

```
------------------------------- MODULE System -------------------------------

CONSTANT Input

Assumptions == Input = 0
ASSUME Assumptions

=============================================================================
```

```
------------------------------ MODULE SystemMC ------------------------------

S == INSTANCE System WITH Input <- 1

Assumptions == S!Assumptions
ASSUME Assumptions

=============================================================================
```

The pattern is a bit silly-looking, but I have found it is very helpful to catch problems early when refining specifications with complicated assumptions.

**Comment by lemmy** [comment]
Minor compaction of Calvin's technique:

```tla
------------------------------- MODULE System -------------------------------


CONSTANT Input

ASSUME Assumptions == Input = 0

=============================================================================
------------------------------ MODULE SystemMC ------------------------------

S == INSTANCE System WITH Input <- 1

ASSUME S!Assumptions

=============================================================================
```

**Comment by ahelwer** [comment]
Over time I've drifted to thinking of this as a feature, not a bug, since sometimes you want to instantiate modules in a way breaking the ASSUME statements in that module.

**Comment by lemmy** [comment]
What do we think about emitting a startup warning (along with hinting at the above workaround) to alert users that assumptions in instantiated modules are not checked? This wouldn’t change TLC’s behavior, but it could help avoid surprises. Apalache also doesn’t check assumptions in instantiated modules, so TLC and Apalache are consistent in this respect.

@konnov, would you support adding a similar warning in Apalache?

/cc @craft095

**Comment by konnov** [comment]
> What do we think about emitting a startup warning (along with hinting at the above workaround) to alert users that assumptions in instantiated modules are not checked? This wouldn’t change TLC’s behavior, but it could help avoid surprises. Apalache also doesn’t check assumptions in instantiated modules, so TLC and Apalache are consistent in this respect.
> 
> [@konnov](https://github.com/konnov), would you support adding a similar warning in Apalache?
> 
> /cc [@craft095](https://github.com/craft095)

We could print a general warning that assumptions of the instantiated modules are omitted. If we have to emit such a warning only under the condition that there are assumptions in instantiated modules, then it's probably as hard as checking them as well. I feel like very few people read warnings and text these days though.

**Comment by lemmy** [comment]
TLC [has behaved this way](https://github.com/tlaplus/tlaplus/issues/156#issuecomment-694547090) for ~30 years, and there are cases where evaluating instantiated ASSUMEs is desirable and cases [where it is not](https://github.com/tlaplus/tlaplus/issues/156#issuecomment-1953204302). We don’t have a sufficiently compelling reason to change the default after all this time.

There is also a potential cost to evaluating these assumptions that may be surprising. An ASSUME can be computationally expensive to evaluate, particularly given how constants can be defined as part of a refinement mapping. Automatically evaluating instantiated assumptions could therefore introduce non-obvious runtime costs.

That cost may be less of a concern for Apalache, but I think the community also benefits from consistent behavior across the TLA+ tools where that is practical.

At the same time, I do think the current behavior needs to be made more visible. Humans may not always read warnings or error messages carefully, but agents generally do. Right now, agents tend to rediscover this behavior over and over again because there is nothing that tells them what TLC is doing.

@craft095 proposed offline adding a command-line option or configuration flag that forces evaluation of instantiated ASSUMEs. That would address the needs of users who know about the option, but it does not help users who are unaware of this behavior in the first place. In practice, such a flag would probably need to be accompanied by a warning or informational message anyway so that users discover that the option exists.

Given that @Calvin-L's [workaround proposed above](https://github.com/tlaplus/tlaplus/issues/156#issuecomment-1069282620) appears straightforward enough, my preference would be to preserve the existing default behavior and improve the diagnostics around it rather than change the default or add another flag.
