### ISSUE TITLE
Display warning to user if TLC finds no behaviours satisfying the spec

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#161]
As discussed in the TLA+ Google Group [here](https://groups.google.com/forum/#!topic/tlaplus/ox2AI3VqPbw): the linked spec _looks_ valid, but actually no behaviors satisfy the Spec formula and so all temporal properties are automatically true. It might be a good idea to display a warning to the user if no behaviors satisfy the spec when checking liveness properties. This could be an option similar to the Deadlock checkbox in the "What to check?" dropdown.

**Comment by lemmy** [comment]
"indeed, there are many ways in which a formal specification can be insignificant, and most specifications are initially wrong. Model checking in particular is most informative when it returns a counter-example, not when it says that the property holds, which may be vacuous. Section 14.5 of "Specifying Systems" contains good advice on how to use TLC – in particular, look at the paragraph "Be Suspicious of Success" in 14.5.3. Inspecting the coverage information and the number of (distinct) states that TLC encountered is mandatory. Since running TLC doesn't require much effort, one should also check properties that are expected to be false and inspect the counter-example that TLC finds in order to build confidence in the specification. For example, you could have checked the invariant

\A u \in User : permissions[u] = {}

which you expected to be wrong because some permissions should be granted.

Your case is extreme in that there are no behaviors (although the safety part by itself has the trivial stuttering behavior), and perhaps TLC could detect this and output a warning. But there are less drastic cases that would still slip through, so it would be of limited use." [Stephan Merz](https://groups.google.com/d/msg/tlaplus/ox2AI3VqPbw/v7RIK4pQBQAJ)

**Comment by ahelwer** [comment]
Similar issue: https://groups.google.com/d/msg/tlaplus/secG-IPKCcI/H_ubarsLEQAJ

**Comment by ahelwer** [comment]
Another one: https://stackoverflow.com/a/75580825/2852699
