### ISSUE TITLE
Invalid violation of a liveness property because of bidirectional transitions in liveness graph due to inverse action

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#201]
Giving the following spec:

```
---- MODULE main ----
EXTENDS Naturals
VARIABLE x

A == x' = (x + 1) % 3
B == x' \in 0..2

Init == x = 0
Next == (A \/ B)

Spec == Init /\ [][Next]_x /\ WF_x(A)
====
```

And any of `Spec`, `WF_x(a)`, or ` []<><<A>>_x` as a temporal property will produce the following error trace:

![image](https://user-images.githubusercontent.com/2660212/47236955-3bba5f80-d3a3-11e8-801a-c264b8403e03.png)

This trace is not a violation of any of those properties. See discussion [here](https://groups.google.com/forum/#!topic/tlaplus/aKt_AuP1i5I).

Note that writing `B == x' \in {0, 1}` will not trigger the bug, despite the error trace never setting `x' = 2`.

**Comment by lemmy** [comment]
The root cause of this problem is that TLC's [LiveWorker#checkComponent](https://github.com/tlaplus/tlaplus/blob/dc4c3bc4570591599609b9b705f806f138a8c5b1/tlatools/src/tlc2/tool/liveness/LiveWorker.java#L503) does not check the actual strongly connected component (SCC) but just the set of states the SCC consists of (```comStack```).

Lets consider the following spec (more explicit than the one above) which corresponds to the state graph below:

```tla
---------------------------- MODULE Liveness ----------------------------
EXTENDS Naturals
VARIABLE x
-------------------------
A == x' = (x + 1) % 4
B == IF x = 0 THEN x' = 3 ELSE  x' = x - 1 
-------------------------
Spec == (x=0) /\ [][A \/ B]_x /\ WF_x(A) 
===========
```

The state graph consists of two subgraphs A and B s.t. A and B are complements of each other.


![graph](https://user-images.githubusercontent.com/88777/47390009-d26d8000-d705-11e8-9c66-c0ff9088fe9d.jpg)



It is partially related to liveness checking under symmetry, which is (currently) unsupported.

**Comment by lemmy** [comment]
@hwayne d784bdd fixes the issue. Since the fix is at the heart of liveness checking, I'd appreciate an extra level of scrutiny by at least an independent reviewer. Thx

**Comment by lemmy** [comment]
d784bdd29294caaa7091b60c06e6ae245da0cb68 is incomplete as TLC produces a bogus counterexample if weak fairness is changed from action A to B.
