### ISSUE TITLE
Improve first-user experience by including or linking to the TLA+ examples 

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#223]
The current Toolbox links to the existing TLA+ examples at "Help" > "TLA+ examples". This is rather hard to find. A rewording of the Toolbox's welcome page could include a link to the examples maybe even with a short introduction shown in the Toolbox.

Alternatively, the Toolbox could include [a subset](https://lamport.azurewebsites.net/tla/more-stuff.html) of the examples in the Toolbox.

--------

The existing NewSpecWizard could be enhanced to accept not just paths but also URLs.  Importing an example spec would then amount to opening the NewSpecWizard with a pre-populated URL pointing to an example spec.  Problem with this idea:
* NewSpecWizard would need an additional page to select the local path where to create the spec
  * => Create specs when created from a URL in the Toolbox's workspace
* How to handle specs consisting out of multiple modules?

A more basic question is, if just adding an example spec makes for a good first user experience.  Taking it one step further, the Toolbox could bundle an RCPTT "test" that demos the Toolbox features but creating an example spec, adding a model, running TLC, visualizing the state space (depends on #199) and showcase the trace explorer.

@quaeler Comments/Thoughts?

**Comment by quaeler** [comment]
The Welcome page could be improved in a few ways; in the least, we should do some modernization of it to current aesthetic design, and add links to:
* the examples page
* Hillel's learning site
* the Google group
* ? your Twitter feed
* ? the GitHub repository

We could also fetch remote content to populate here.

-------------------

To accommodate a change like that to the NewSpecWizard we should consider introducing an Export Specification in the Toolbox which produces an archive containing all module files in addition to the model directory. Once we have this, we should add the Export versions of the examples repository's specifications to a publicly accessible web site; with this in place, it is a small-ish implementation to have a "browse and choose from the examples server" aspect of the spec loading, and a smaller implementation to allow importing the archive.

-------------------

I think a problem with bundling RCPTT is the way that RCPTT must weaving in its instrumentation in order to work; i don't think we want the toolbox always running like this, and there's no good way that comes to mind to know ahead of launch that a user may want to run such an example.

**Comment by lemmy** [comment]
This is what it looks like in my prototype.  The buttons will import the example into the Toolbox.

![Screenshot from 2019-04-05 15-35-11](https://user-images.githubusercontent.com/88777/55659892-7af53500-57b8-11e9-9270-b2c8ce12bc7e.png)


Unfortunately, it seems impossible to programmatically download a zip archive for a subdirectory of a GitHub repository.

**Comment by lemmy** [comment]
![WelcomescreenExamples2](https://user-images.githubusercontent.com/88777/55687612-d132b700-5923-11e9-850b-f42007134fe5.gif)

**Comment by lemmy** [comment]
393bbb29fbf08d67175ee49724a1a6b5aefd2965

![WelcomeScreenExamples](https://user-images.githubusercontent.com/88777/55844281-68009e80-5af1-11e9-8112-ac18f22c35a1.png)
