### ISSUE TITLE
M1+N should be a key map for Add New Spec

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#294]
We should map the action for 'Add New Spec...' to the keybinding of M1+N

**Comment by lemmy** [comment]
M1+N currently opens Eclipse's new wizard from where (since recently) it is possible to create a new TLA+ specification.  However, the new wizard also offers to create a bogus "General" section which should be removed.  Ideally, M1+N would also be context sensitive and offer to create a spec or a model depending on the Spec Explorer's current selection.

**Comment by lemmy** [comment]
Related: #299
