### ISSUE TITLE
Warn when PlusCal and TLA+ transpilation diverge

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#296]
Problem
-----------
The Toolbox workflow involving PlusCal and TLC consists of the following steps:

1. Modify PlusCal
2. (Automatically) Transpile to TLA+
   (Optionally) go back to 1.
3. (Optionally) modify TLA+
4. Run TLC
5. Rinse and Repeat

If a user accidentally misses step 2. before finally running TLC, model checking produces surprising/unexpected results. Thus, TLC (Toolbox) should raise a warning if a PlusCal algorithm and its TLA+ transpilation have diverged.  Likewise, TLC should warn if the TLA+ has been modified after transpilation.

Proposal
------------
Let the PlusCal translator prepend the hash value - similar to a message digest but without cryptographic guarantees ([SHA](https://en.wikipedia.org/wiki/Cryptographic_hash_function)) - of the PlusCal input to the transpiled TLA+. In order to detect (intended) modification of the transpiled TLA+, the PlusCal translator appends the hash value of the TLA+.  When parsing the TLA+ specification, TLC can emit a warning if the actual PlusCal and TLA+ mismatch with the respective hash values. 

When TLC is launched from the command-line on a spec that has diverged, TLC prints a warning but continue model checking.  When TLC is launched from the Toolbox, a dialog would allow users to 1) ignore the warning and continue model checking, 2) re-transpile PlusCal to TLA+ and continue model checking, or 3) abort model checking.

Stretch goal:  Show users the differences without re-transpilation by opening the diff viewer.

**Comment by lemmy** [comment]
This feature might help with #157

**Comment by lemmy** [comment]
Is a checksum of 256 bits (SHA 256) really necessary?   I'd assume a shorter/faster md5 is good enough for our (non-crypto) purpose.

**Comment by quaeler** [comment]
Excessive because it is too long of a goobly-gook string staring at the user in their spec, or excessive because it is ~heavier computationally?

**Comment by lemmy** [comment]
Both :)

**Comment by quaeler** [comment]
:- ) ok.. will go to md5

**Comment by lemmy** [comment]
Will String#hashCode work?

**Comment by lemmy** [comment]
It seems both hash values are prefixed with "PC-" and "TPC-".  I suggest to change the prefixes to "PCal-" and "TLA-" to indicate what they are.

**Comment by alygin** [comment]
> Excessive because it is too long of a goobly-gook string staring at the user in their spec, or excessive because it is ~heavier computationally?

> Both :)

Speaking of hash value lengths, the common approach is to just take several characters from hash values and leave the rest out. Git, for instance, uses only first 7 characters of the commit SHA1 hash code to identify commits.

For the purpose of detecting a discrepancy in two text blocks it could be even shorter if needed, the collision is extremely unlikely.

**Comment by alygin** [comment]
BTW, I was also thinking of warning the user if she tries to modify TLA code inside the translation block. Some IDEs do that for autogenerated code.

It doesn't solve all the problems this proposal aims, yet provides a quicker response and prevents switching to unhappy path (the one with divergence) in some cases.

Could be a supplementary feature to all these changes. What do you think?

**Comment by lemmy** [comment]
The TLA+ translation shouldn't be considered auto-generated code, ie. it frequently happens that one modifies - e.g. add Print statements - the TLA+ while working on a PlusCal spec.

**Comment by alygin** [comment]
Yet at the moment when the user starts to modify this TLA+ code it _is_ auto-generated. But wording is not what I want to dwell on here. Let's look at the use case you just described and how it's going to work after the changes:

1. The user has a PlusCal algorithm and the corresponding TLA+ code.
2. He edits this TLA+ code because wants to add some debug info or just accidentally.
3. He runs TLC.
4. The toolbox issues a warning with options: re-transpile, continue, cancel.

If he hits "re-transpile" he immediately loses all his changes, which doesn't sound right if he made them on purpose.

If he hits "continue", the process continues. He gets what he wanted. That's the only happy path.

If he hits "cancel"... Stop, why would he do that in the first place? Only because hi realizes what he just did, and that he actually didn't want to do that (to edit the TLA+ code). In this case he has to move all his changes to PlusCal, transpile, and run TLC.

So, we have three options here, and only one of them doesn't lead to an upset user. It leaves me with the feeling that it could be better than that. Hence my suggestion.

**Comment by lemmy** [comment]
The Toolbox preserves a history of edits, hence nothing gets lost. Thanks for suggesting though that the Toolbox should show the differences between the original TLA+ and the modified one to allow users to make informed choices. That is definitely a feature for the next iteration.

The tooling should encourage users to become familiar with TLA+ because it is more expressive than PlusCal (which is just a "gateway drug"). Thus, divergence is not leading to the unhappy path, especially for users already familiar with TLA+.  Warning users that they are about to modify generated TLA+ should - if at all - only be done once to instruct users how to access the history.  The editor shouldn't require users to acknowledge a warning every time they modify the original TLA+.

**Comment by alygin** [comment]
Oh, I didn't mean the warning should appear every time the user changes something. It should be more intelligent. Otherwise, it would be a torture )

The implementations I'm aware of only ask once if you know what you are doing, and don't bother you anymore if you answer Yes (until you close the file). In case of the Toolbox the answer Yes would also mean not asking if you really want to start TLC without syncing the PlusCal and TLA+ code. The difference is in preventing user mistakes instead of just telling the user that they made a mistake (because that's what two of three warning options now mean) and waiting for them to fix it somehow (and history of edits is of little help if you need to move changes from the translation-block to a proper place).

I totally agree on encouraging users to use TLA+, but the practice of having TLA+ code converged from its PlusCal algorithm doesn't seem right.

But that's my own experience and thoughts on the issue, don't want to impose them.

**Comment by lemmy** [comment]
Here is a workflow that could be better supported:
1) Generate TLA+ from PlusCal
2) Modify TLA+ (add a print statement)
3) TLC complains that PlusCal and TLA+ are out-of-sync
4) User ignores warning for the current Toolbox session
5) User modified PlusCal but forgets to re-translate

Instead of ignoring the warning in 4), a user could make her intent explicit by removing the second/TLA+ hash string from the spec causing the Toolbox to still show the warning when the PlusCal diverges:

1) Generate TLA+ from PlusCal
2) Modify TLA+ (add a print statement)
3) Remove second/TLA+ hash
4) Toolbox & TLC only raise warning when PlusCal has been modified

**Comment by quaeler** [comment]
Implemented suggestion, and updated changelog and help text, with 4490df2

**Comment by quaeler** [comment]
I believe this to be implemented; please re-open if i have missed something.

**Comment by lemmy** [comment]
TLC incorrectly warns about a stale translation.

```tla
------------------------- MODULE FairBlockingQueue -------------------------
EXTENDS Naturals

VARIABLE x

Spec == x = 0 /\ [][UNCHANGED x]_x

=============================================================================

(***************************************************************************
--algorithm Algo {
}
 ***************************************************************************)
```
