### ISSUE TITLE
TLC does not evaluate all CASE branches

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#32]
Code:

```
EXTENDS TLC

VARIABLES x

Next == Assert(x = TRUE, "Failed") /\ UNCHANGED x

Init == x = CASE TRUE -> TRUE 
            []   TRUE -> FALSE

Spec == Init /\ [][Next]_x    
```

Expected: Spec fails.
Actual: Spec passes.

Notes: If we replace Init with `x = CHOOSE p \in BOOLEAN : (TRUE /\ p = TRUE) \/ (TRUE /\ p = FALSE)`, as per formal semantics on 298 of _Specifying Systems_, the spec fails as expected.

**Comment by pron** [comment]
That is not the semantics of `CASE`. See p. 298 of *Specifying Systems*:

> If some p_i is true then the value of the expression is *some* e_i such that p_i is true.

Because in the first case the condition is `TRUE`, the CASE expression is allowed to be equal to the result of the first case, which is `TRUE`. Like `CHOOSE`, `CASE` is not nondeterministic and the model checker does not try all possibilities. Your example with `CHOOSE` is no different from `CHOOSE p ∈ BOOLEAN : TRUE`, an expression which according to TLA+ semantics may be either always `TRUE` or always `FALSE`. It seems like TLC chooses `FALSE`, as it is allowed, but it could have just as easily chosen `TRUE`.

**Comment by johnyf** [comment]
The transition to a next state during evaluation of a `CASE` statement seems to be in [`tlatools/src/tlc2/tool/Tool.java#L1500`](https://github.com/tlaplus/tlaplus/blob/770a070649e89e21487ffeea3fab50e02bcfff32/tlatools/src/tlc2/tool/Tool.java#L1500).

**Comment by hwayne** [comment]
@pron is right; turns out I misunderstood how TLC handles both `CASE` and `CHOOSE`.
