### ISSUE TITLE
TLC model checker: "Deadlock" checkbox appears blank even if checked

### ISSUE THREAD

**Issue by DestyNova** [tlaplus/tlaplus#351]
While following the video tutorials and attempting to run the TLC model checker, my model failed due to a "deadlock" (meaning, termination of the program).

When I went back to uncheck the "Deadlock" option, it appeared already unchecked, but TLC still fails with the same error.

After some investigation, it seems that the "checked" checkbox looks empty except for a thin green border:

![Screenshot from 2019-08-13 00-15-49](https://user-images.githubusercontent.com/1646628/62904795-a4722e80-bd5f-11e9-9ec6-d553dfc170ae.png)

...and the "unchecked" checkbox looks the same except with a thin grey border:

![Screenshot from 2019-08-13 00-15-59](https://user-images.githubusercontent.com/1646628/62904807-b48a0e00-bd5f-11e9-9981-d7b8ccc93c3f.png)

If it's any help, I'm running Ubuntu 19.04 on an x64 machine, using Java 1.8:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~19.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

**Comment by quaeler** [comment]
Assuming this is 1.6.0, the Java version is immaterial - the Toolbox now ships with its own JRE (presently Adopt OpenJDK 11).

This sounds like an SWT implementation issue - perhaps you can [find an existing issue in Eclipse's bug tracking system?](https://bugs.eclipse.org/bugs/buglist.cgi?classification=Eclipse&component=SWT&list_id=18890152&product=Platform&query_format=advanced)

**Comment by DestyNova** [comment]
Yes, I should have mentioned the toolbox version which is indeed 1.6.0. I did a quick search of the Eclipse bug tracker and couldn't find anything relevant, but there are hundreds of matches for the search term "checkbox" so I'll try to have another look later.

**Comment by mnp** [comment]
I'm still seeing this in 2020 in 1.6.0. It's also on the "No Behavior Spec" check box.

**Comment by lemmy** [comment]
Try launching with `/path/to/TLA+Toolbox/toolbox -cssTheme none`

**Comment by mnp** [comment]
Thanks for the experiment.  The `cssTheme none` switch definitely has some minor style effects but specifically for the check boxes, they look the same as OP's images.

**Comment by lemmy** [comment]
@mnp please provide more information about your OS, window manager, theme, ...

**Comment by mnp** [comment]
Okay kind of solved: @lemmy 's question was exactly the right thing to ask.

Ubuntu 19.10, X11 session type, GDM and gnome-tweak to flip themes.  

So it turns out that Gnome themes can indeed affect UI elements inside Toolbox, and the checkbox is highly dependent on the theme.  Some themes highlight the marked state, and some obscure it. Three examples (Adwaita, Ambience, and High Contrast, respectively):

![adwaita](https://user-images.githubusercontent.com/881925/79482574-049c2d00-7fdf-11ea-8ca0-573ef6a8de79.png)  ![ambience](https://user-images.githubusercontent.com/881925/79482575-0534c380-7fdf-11ea-8e3d-d3834c2efd23.png)  ![high-contrast](https://user-images.githubusercontent.com/881925/79482577-0534c380-7fdf-11ea-9c8d-64367b5abb99.png)

Toolbox users can choose a different theme, plus it seems some themes should support the Eclipse elements better.

Thanks!

**Comment by lemmy** [comment]
I don't see what we can do about except waiting for Eclipse to address the issue.  Would somebody of those affected please open an [Eclipse bug](https://bugs.eclipse.org)?
