### ISSUE TITLE
Disable TLA+ toolbox performance hint notification?

### ISSUE THREAD

**Issue by arssher** [tlaplus/tlaplus#402]
Hi,

While running TLC, sometimes a notification appears hinting to turn off the profiling to speed up the checking process. Of course I can do that, but nevertheless I find surprising that I've failed to find how to disable the notifications entirely. Is it possible?

**Comment by lemmy** [comment]
No, it's not possible to disable the notification. The Toolbox generally tries to be as non-intrusive as possible but in this case---because the overhead is noticeable---we feel it is important to show the hint.  Can you please describe why you not just ignore the hint?  Does it somehow get in the way?

**Comment by arssher** [comment]
Well, yes, since it appears (regularly) not just in the toolbox but over any application it is somewhat distracting. Probably it would be better to show it once in one TLC run. But I can live with profiling disabled, especially if it indeed has significant overhead; it is a minor issue anyway, thanks.

**Comment by lemmy** [comment]
Great, I'm going to close this since the hint appears to have the desired effect after all. ;-)
