### ISSUE TITLE
org.eclipse.preferencePages not found

### ISSUE THREAD

**Issue by introom** [tlaplus/tlaplus#410]
![image](https://user-images.githubusercontent.com/669045/71517969-6f6c1000-28eb-11ea-8bcb-b5314fb9643d.png)

**Comment by lemmy** [comment]
This is not really a bug but an artifact of the Toolbox stripping the preferences of Eclipse specific settings that are not relevant in its scope.  A proper fix would require a change in Eclipse.  Given that the warning is annoying but has otherwise no impact, we won't be working on this in the foreseeable future.
