### ISSUE TITLE
raising an error for positional reference to theorem assumption that is a declaration

### ISSUE THREAD

**Issue by johnyf** [tlaplus/tlaplus#427]
```tla
------------------ MODULE PositionalReferencesToAssumptions -------------------
(* Using positional references to assumptions of a theorem ? *)
THEOREM Thm ==
    ASSUME CONSTANT r
    PROVE TRUE
PROOF
BY ONLY Thm!1  (* SANY does not raise an error. *)
================================================================================
```

**Comment by xxyzzn** [comment]
The documentation does not seem to indicate whether Thm!1 is legal, or what it should mean if it is legal.  For example, consider this theorem:

    THEOREM Thm ==
       ASSUME CONSTANT r \in Nat
       PROVE  r+1 > r

It would make sense for Thm!1 to mean r \in Nat inside the theorem's proof.  In that case, in the original example, Thm!1 would logically mean TRUE.

Since SANY does not allow Thm!1 outside the proof (since r is undefined there), and since TLAPS doesn't accept Thm!1 inside the proof, there is no point trying to decide if this is a bug or not.

**Comment by johnyf** [comment]
Thank you very much for your answer.
