### ISSUE TITLE
Cannot instantiate module variables with lambdas

### ISSUE THREAD

**Issue by anton-trunov** [tlaplus/tlaplus#458]
It looks like the [TLA+ grammar in TLA+](https://lamport.azurewebsites.net/tla/TLAPlus2Grammar.tla) allows one to instantiate module variables with lambdas, because a `G.Lambda` is a `G.Argument`.

However, the following snippet fails with a parse error:
```
------------------------------- MODULE lambda -------------------------------

---- MODULE module  ----
VARIABLE inc
========================

INSTANCE module WITH inc <- LAMBDA x: x + 1

=============================================================================
```

Here is the error I see
```
LAMBDA expression used where an expression is required
```

I'm using TLA+ Toolbox 1.7.0.

**Comment by xxyzzn** [comment]
The INSTANCE statement is clearly incorrect, because substituting an operator for a variable produces a grammatically incorrect expression.  And the error message clearly states why it is incorrect.  Not every sequence of tokens allowed by TLAPlus2Grammar is grammatically correct--for example, it does not rule out the expression x''.    More to the point, if Op1 is a declared CONSTANT operator of module M that takes 1 argument, and if  Op2 is an operator that takes 2 arguments defined in a module that instantiates M, than an INSTANCE with the substitution Op1 <- Op2 is illegal, even though it's not ruled out by TLAPlus2Grammar.   The example in this report is similar, except it's substituting an operator that takes 1 argument for an operator that takes 0 arguments.

**Comment by anton-trunov** [comment]
> Not every sequence of tokens allowed by TLAPlus2Grammar is grammatically correct

Now it makes sense, thank you so much!
