### ISSUE TITLE
"JCloud distributed TLC provider" potentially not installed

### ISSUE THREAD

**Issue by qwitwa** [tlaplus/tlaplus#46]
I recently upgraded my TLA Toolbox installation using the internal updater from version 1.5.2 to 1.5.3 and attempted to use the new cloud TLC feature with Azure, following the instructions to generate certificates and set the relevant environment variables. 

Upon clicking the run button, nothing appeared to happen, so as per the help file I ran the toolbox with -console and -consolelog. The console spawned has a limited scrollback buffer but I have copied what I could and attached the log. 

The error message asks me to look to see if the "JCloud distributed TLC provider" is installed, and if not, to report a bug. I found a component with a similar name, but not one with that exact name.  I've attached a screenshot. 
![tla toolbox installed software screenshot](https://cloud.githubusercontent.com/assets/2302478/25686263/e57603e6-3064-11e7-9b25-2d06ae02cbbc.png)

[log.txt](https://github.com/tlaplus/tlaplus/files/974958/log1.txt)

**Comment by lemmy** [comment]
Hi @qwitwa,

thanks for taking the time to report this bug. I was able to reproduce it locally. Running TLC on Azure or EC2 for that matter is indeed broken when the Toolbox is updated from 1.5.2. does work however, if 

and track it down to the offending commits 

- Broken when Toolbox is updated from 1.5.2. Does not happen with fresh install. Reasons unknown
- Azure broken in 1.5.3 anyway, due to an EC2 optimization introduced with commit 69851b2efc97ecd2337a52112beaba6cb669018a
- => Use most recent nightly build (only little difference to 1.5.3)
