### ISSUE TITLE
Model editor wastes screen estate

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#49]
Let model editor make better use of screen estate. Especially:

- Result Page
  - General (alignment values)
  - Statistics (horizontally)
  - Progress Output (vertically)

**Comment by lemmy** [comment]
A relatively trivial enhancement would be to be able to change the vertical size of the „evaluate constant expressions“ input box.

**Comment by quaeler** [comment]
Since adding an expression to the "Evaluate Constant Expressions" text area both dirties the model and seeming requires a model checker execution to spur the evaluation, shouldn't this section be moved to either the "Model Overview" page or the "Advanced Options" page (... since items on the Results Page are all read-only) ?

**Comment by lemmy** [comment]
@quaeler That's an interesting idea, but the overview page is already quite loaded. The "Evaluate Constant Expressions" could be moved to a dedicate tab or even its own view. Let me first find out the reasons why it's on the Results Page though.

**Comment by lemmy** [comment]
Also see #162

**Comment by parlarjb** [comment]
It'd be helpful to be able to increase the text size in the model editor. It would greatly help accessibility, but I have an additional use for it:

I spent a lot of time teaching people TLA+ over a screen share. Depending on the size of their screen, their resolution, the size of their video share window, etc., it can be very difficult for them to see what I'm doing in the model checker. Teaching remotely would be greatly aided by being able to increase the text size here.

**Comment by lemmy** [comment]
https://twitter.com/tummycom/status/1111375890896703488

**Comment by lemmy** [comment]
Two more annoyances with Evaluate Constant Expressions:

1. Moving the cursor right on an existing expressions additionally scrolls the Result Page (unless it fits the available horizontal space)
2. Running model checking steals focus from Evaluate Constant Expressions (one has to reselect ECE after running TLC)

**Comment by quaeler** [comment]
(1.) of the annoyances is a feature of SWT (i can kind of, sort of, see a valid accessibility use-case - so that is tempering my usual sniping on the kwality of SWT.) It will happen with other text areas, too - like the User Output.
It might be less annoying if dbe09ba sticks as a keep-able feature as it allows the page to be even more narrow before forcing the horizontal scrollbar.

**Comment by quaeler** [comment]
(2.) of the annoyances is addressed by the cherry-pick to master with 8bc49ab

**Comment by lemmy** [comment]
8bc49ab does not appear to work on Linux.

**Comment by quaeler** [comment]
Works on both Mac and Win10... SWT!

**Comment by quaeler** [comment]
Verified the crappy behavior on Ubu18.04 - know idea where the focus is being sent, but if i hit tab once, it magically shows up where it should be on Ubu.

**Comment by lemmy** [comment]
That's good enough for me.

Another way to lose focus is when the ECE expression results in a TLC error.  The Toolbox then opens the error trace explorer which steals focus.  Lets not work on this for the moment though.

**Comment by quaeler** [comment]
as agreed with mku in email, there are no specific outstanding issues keeping this open, so i am closing it.
