### ISSUE TITLE
application and DOMAIN of strings in TLC

### ISSUE THREAD

**Issue by johnyf** [tlaplus/tlaplus#512]
It would be nice if TLC supported function application `f[i]` and `DOMAIN f` when `f` is a string and when `i \in DOMAIN f`. Currently errors are raised, for example the following module:

```tla
---- MODULE Strings ----
EXTENDS Integers


ASSUME "abc"[2] = "b"[1]

ASSUME (DOMAIN "ab") = 1..2

========================
```

results in the following errors (the second error arises after commenting the first `ASSUME` above):

```
Error: Evaluating assumption line 5, col 8 to line 5, col 24 of module Strings failed.
A non-function (a string) was applied as a function.
line 5, col 8 to line 5, col 15 of module Strings
```

and

```
Error: Evaluating assumption line 7, col 8 to line 7, col 27 of module Strings failed.
Attempted to apply the operator DOMAIN to a non-function
(a string)
line 7, col 9 to line 7, col 19 of module Strings
```

This issue is relevant to #159.

**Comment by hwayne** [comment]
Fun fact, because the `Sequences` module uses Java overrides, you can use operators from that module on strings. So like `Head(str)` works.

**Comment by xxyzzn** [comment]
There is indeed a bug here--the one reported by hwayne.  TLC incorrectly evaluates Head("abc") to equal "a".  Head("abc") equals "abc"[1].  Since TLC reports that it can't evaluate "abc"[1], it should produce the same error message when evaluating Head("abc").

The semantics of TLA+ do not specify the value of "abc"[1], just as they do not specify the value of "abc"[5].  They do specify that "abc"[1] is unequal to "abc"[3], and TLAPS will prove that.  To allow TLC to compute "abc"[1] # "abc"[3], it would have to be modified to handle a completely new "character" data type and print out the character 'a' as "a"[1].  If TLC were carefully designed, that should not be too difficult.  But  I doubt if it was that carefully designed.   Anybne welcome to give it a try.  If it's possible to do it in a way that we can be sure will not introduce bugs in anything it now does, we'd be happy to add that feature to TLC.

Now, TLC should  be able to evaluate any expression that does not produce a value like "abc"[1].  For example, it can evaluate Head("abc").

**Comment by zwergziege** [comment]
I started working on this (after flooding you with issues, today I thought I'd try something nice). 
Here is what I have tested so far:
```
a == "abcd"
b == [x \in DOMAIN a |-> a[x]]
c == "bcd"
A == "a"[1]

ASSUME a = b
ASSUME DOMAIN a = 1..4
ASSUME a[2] = c[1]
ASSUME (a \o c) = (b \o c)
ASSUME <<A,A>> = "aa"
ASSUME <<A,A>> \in Seq({A})
```
Care to look at it? Be warned though. It's only a day's work of a Java noob who started looking at your codebase only yesterday.

**Comment by lemmy** [comment]
Closing given `1..Len("abc")` from `Sequences` as the slightly more verbose alternative to `DOMAIN "abc"`.  Supporting the latter would require for `StringValue` to implement `tlc2.value.impl.Applicable`.

Please reopen providing a PR that adds a proper character data type as mentioned by @xxyzzn above.

**Comment by zwergziege** [comment]
see #685

**Comment by ahelwer** [comment]
Sad to report that `head` and `tail` no longer work on strings on nightly. RIP.

**Comment by lemmy** [comment]
TLC2 Version 2.18 of Day Month 20?? (rev: 05381d2)

```tla
(tla+) Tail("abc")
"bc"
```

**Comment by ahelwer** [comment]
Ah I suppose `Tail` still works, I just assumed it didn't. `Head` does not:
```
[ahelwer@node LeastCircularSubstring]$ java tlc2.REPL
Welcome to the TLA+ REPL!
TLC2 Version 2.18 of Day Month 20??
Enter a constant-level TLA+ expression.
(tla+) Head("abc")
Error evaluating expression: 'Head("abc")'
tlc2.tool.EvalException: The argument of Head should be a sequence, but instead 
it is:
"abc"
```

**Comment by lemmy** [comment]
Head's behavior has indeed been reverted to `EvalException` for the reasons stated above.

**Comment by xxyzzn** [comment]
The value of Head("abc") is not specified by the semantics of TLA+.

**Comment by ahelwer** [comment]
I thought TLA+ strings were 1-indexed sequences, and it's only by shortfall of TLC that they are not actually able to be used that way?

**Comment by xxyzzn** [comment]
They are 1-indexed sequences, but what they are sequences of is unspecified.  This implies that <<Head("abc")>> equals "a", but it doesn't say what Head("abc") equals.  Unfortunately, TLC is not smart enough to realize it can evaluate <<Head("abc")>> without evaluating Head("abc").  But there are lots of expressions TLC can't evaluate even though it can express their values.

**Comment by ahelwer** [comment]
Got it, so the language spec itself lacks the concept of a character type. I suppose this isn't the worst thing in the world, modern strings are best represented by ordinals with `Seq(Nat)` anyway. It might be nice to have a method (maybe in TLC or some other standard module?) to convert between strings and `Seq(Nat)` though, just for ease of input and reading output.

**Comment by xxyzzn** [comment]
That sounds like a nice community module.
