### ISSUE TITLE
Accessing State Space

### ISSUE THREAD

**Issue by yashFrost97** [tlaplus/tlaplus#523]
Hello!
I'm exploring Model-based Test Case Generation and for that, I need a way to access states generated by the model. I looked at the Graphviz DOT extension to visualize the State Graph [(Stackoverflow Link!).](https://stackoverflow.com/questions/52055716/tla-how-to-visualize-the-state-graph) 
It generates the state graph as a PDF and along with it creates 2 additional files (they are word files in my system). I understand these 2 files are being used by the GraphViz extension to generate the graph (Correct me if I'm wrong!). 
Are these files the way to access the states or is there a better way? (Or am I doing it completely wrong) 

Help Appreciated!

**Comment by lemmy** [comment]
Your system doesn't have a [proper viewer](https://graphviz.org/resources/), which is why it opens the [`.dot`](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) files in Word.  See the `dot` [tool](https://graphviz.org/pdf/dotguide.pdf) how to generate e.g. SVG, PNG, ... from the `.dot` files (one is the liveness graph, the other the plain state graph).

At the moment, the `dot` file is the best, but not an efficient way to get hold of the state graph generated by TLC.  The [Kayfabe](https://www.youtube.com/watch?v=lj31oIaYSj4&list=PLWLcqZLzY8u8EA8UlsZ5xKMvtUoeGr5R_&index=13) tool takes the (plain) .dot file as input for model-based testing.

**Comment by yashFrost97** [comment]
Thank you so much Markus! I'll look into an appropriate viewer for my system! Thanks!
Cheers!
