### ISSUE TITLE
Visualizing State Space

### ISSUE THREAD

**Issue by yashFrost97** [tlaplus/tlaplus#524]
Hello! This issue is related to/continuation of Issue #523 , 
The state-space graph generated takes a very long time to open in the TLA+ toolbox. [(Stackoverflow Link!)](https://stackoverflow.com/questions/52055716/tla-how-to-visualize-the-state-graph) If it loads completely and I save it as a PDF, my PDF viewer again takes a long time to open the file, most of the time it crashes or hangs up. The number of states is 200 for my model. I'm using Windows 10 with an i7 processor (if this info helps!).

Thanks for any help!

**Comment by lemmy** [comment]
For all but tiny state spaces, the PDF generation is expected to time out.  The underlying problem is twofold: a) the dot layout algorithm and b) limitations of pdfs.  You can try rendering the graph (in the `.dot` file) with a different layout algorithm and to a different target (e.g. SVG).  A more powerful tool to look at larger graphs is https://gephi.org.

**Comment by yashFrost97** [comment]
Thanks for your help!
