### ISSUE TITLE
TLA+ Toolbox can't locate pdflatex

### ISSUE THREAD

**Issue by samhavens** [tlaplus/tlaplus#54]
On macOS 10.12.5 and Version 1.5.3 of TLA Toolbox.

```bash
$ which pdflatex
/usr/local/bin/pdflatex
```
But when attempting to pretty print a module from TLA+ Toolbox, I get the following `PDF Production error`:
> TLATeX unrecoverable error: —Trying to run the command `pdflatex SimpleProgram.tex` produced the following error 
>    Cannot run program “pdflatex” (in directory “/Users/samhavens/tla test/ SimpleProgram.toolbox”): error=2, No such file or directory.

I have LaTex installed via MacTex and Texmaker. I have verified that from the command line I can run `pdflatex` on `.tex` files to produce pdfs.

**Comment by lemmy** [comment]
Hi, 

did you try with the pdflatex command set to the complete path "/usr/local/bin/pdflatex" in the Toolbox's preference?

![pdfviewerpref](https://cloud.githubusercontent.com/assets/88777/26531155/660771ca-43e3-11e7-8b21-fc2d2b00648d.png)

**Comment by samhavens** [comment]
@lemmy Thank you, that did it. Sorry for the RTFM question.

**Comment by nyck33** [comment]
Hello, I am on Windows 10, downloaded Milktex as suggested here:  https://tla.msr-inria.inria.fr/tlatoolbox/doc/spec/pretty-printing.html
I installed to C:\cygwin\usr\local\bin\pdflatex and put the same in the Specify latex command box above but getting the same error.  Please advise at your next convenience.

**Comment by lemmy** [comment]
@nyck33 Your path to pdflatex is most likely incorrect. If you want to use pdflatex provided by MikTeX, it will be located inside the MikTeX installation directory, e.g. "c:\Program Files\MiKTeX 2.9\miktex\bin\x64\pdflatex".

**Comment by nyck33** [comment]
@lemmy Thanks so much, it works now.

**Comment by mrhwick** [comment]
Would it be useful to somehow detect the location of an installation of `pdflatex` to make this more seamless?

**Comment by lemmy** [comment]
@mrhwick Definitely, do you have time to work on this?

**Comment by mrhwick** [comment]
I'm not sure what would be involved in order to add that feature for all platforms, and I would need to get my dev environment set up to work on TLA+ at all. I'll take a crack at it when I have spare after-hours time.

Would it make sense to add a detection operation when setting the default preference, or attempting the check at some other time?

**Comment by lemmy** [comment]
@mrhwick https://github.com/tlaplus/tlaplus/tree/master/general/ide shows how to setup your dev environment (you might end up with compiler warnings in *.uitests projects. Just ignore them).

Lets start with a search button on the preference page similar to what Eclipse has on the Window > Preferences > Java > Installed JREs. The corresponding Toolbox preference is at https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.tool.tla2tex/src/org/lamport/tla/toolbox/tool/tla2tex/preference/TLA2TeXPreferencePage.java
If the search later proofs reliable, the Toolbox can eventually search automatically.

**Comment by alanmynah** [comment]
For those who encounter this error on Mac, might not have pdflatex installed in the directory in @lemmy's reply, use `where pdflatex` to paste your path into the editor. And then worked a treat, thanks a lot @lemmy!

**Comment by cmsmcq** [comment]
I am getting the same error report as described by the OP, both before setting the full path to pdflatex and after setting it.  In my case, it reads

> The following error was encountered while attempting to generate the PDF - perhaps you have not set a full path to pdflatex in the preferences?

> TLATeX unrecoverable error: -- Trying to run the command `/usr/bin/pdflatex SimpleProgram.tex' produced the following error
>    Cannot run program "/usr/bin/pdflatex" (in directory "/home/cmsmcq/2023/etudes/tla/SimpleProgram.toolbox"):  error=2, No such file or directory.

On the off chance that the problem might be due to the fact that /usr/bin/pdflatex is a symbolic link, I replaced the path in the Preferences with /usr/bin/pdftex, which elicited a similar error message with the new path.

I also tried restarting the TLA+ Toolbox.  No joy.

As the following fragment of a bash log shows, I am unable to reproduce the failure outside of the TLA+ toolbox.

> cmsmcq@gemma:\~$ cd 2023/etudes/tla/SimpleProgram.toolbox/
> cmsmcq@gemma:\~/2023/etudes/tla/SimpleProgram.toolbox$ pwd
/home/cmsmcq/2023/etudes/tla/SimpleProgram.toolbox
> cmsmcq@gemma:\~/2023/etudes/tla/SimpleProgram.toolbox$ /usr/bin/pdflatex SimpleProgram.tex 
> This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> (./SimpleProgram.tex
> LaTeX2e <2021-11-15> patch level 1
> L3 programming layer <2022-01-21>
> cmsmcq@gemma:\~/2023/etudes/tla/SimpleProgram.toolbox$ 

Help / About reports:
> This is Version 1.7.1 of 31 December 2020 and includes:
>  - SANY Version 2.2 of 20 April 2020
>  - TLC Version 2.16 of 31 December 2020
>  - PlusCal Version 1.11 of 31 December 2020
>  - TLATeX Version 1.0 of 20 September 2017
 
I am running Pop!OS 22.04 LTS on a System76 Galago Pro.

As illustrated, I appear to be able to generate PDF myself, so I do have a work-around.  But I suspect not being able to do so from within the toolbox will eventually become a nuisance.

**Comment by Calvin-L** [comment]
@cmsmcq The error "No such file or directory" is reported in multiple different situations:
 1. The executable (`/usr/bin/pdflatex`) does not exist
 2. The executable exists, but its [interpreter](https://en.wikipedia.org/wiki/Interpreter_directive) does not
 3. The executable and its interpreter both exist, but its interpreter is given as `#!/usr/bin/env <some_program>` and `some_program` cannot be found on `$PATH`.

My first guess is that you are encountering case 3, which can happen if the Toolbox uses a different value for `$PATH` than your shell. (The fact that these all result in the same generic error has cost me many hours of my life, which is why it's my first thought.)

Can you share the output of

    file /usr/bin/pdflatex

(You may need to install `file` using your distro's package manager.)

If `file` reports something like "... text executable ...", can you also share the output of

    head -n1 /usr/bin/pdflatex

which should be something like `#!/usr/bin/env <some_program>`, and the output of

    type <some_program>

where `<some_program>` is in the output you got from `head`?

**Comment by cmsmcq** [comment]
Thank you, @Calvin-L -- good suggestions, and eventually they led me to what I think is the root cause of my problem.

From `file` I get this output:

> cmsmcq@gemma:$ file /usr/bin/pdflatex
> /usr/bin/pdflatex: symbolic link to pdftex
> cmsmcq@gemma:$ file /usr/bin/pdftex
> /usr/bin/pdftex: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f18468448a5dcf0246969b0343dbdaa52fff2fbd, for GNU/Linux 3.2.0, stripped
> cmsmcq@gemma:$ 

So I don't think pdftex is a text executable that needs an interpreter.  

To try to see whether it's a path problem, I tried deleting my path and running pdflatex with PATH set to the empty string.  It works:
````
$ # Is it a PATH problem?  Trying with cleared path.
$ pwd
/home/cmsmcq/2023/etudes/tla/SimpleProgram.toolbox
$ echo $PATH

$ /usr/bin/ls -l
total 44
-rw-r--r-- 1 cmsmcq cmsmcq 42550 Jun 18 19:36 SimpleProgram.tex
$ /usr/bin/pdflatex SimpleProgram.tex 
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./SimpleProgram.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21>
$ /usr/bin/ls -l
total 132
-rw-rw-r-- 1 cmsmcq cmsmcq    32 Jun 18 20:09 SimpleProgram.aux
-rw-rw-r-- 1 cmsmcq cmsmcq  5987 Jun 18 20:09 SimpleProgram.log
-rw-rw-r-- 1 cmsmcq cmsmcq 76135 Jun 18 20:09 SimpleProgram.pdf
-rw-r--r-- 1 cmsmcq cmsmcq 42550 Jun 18 19:36 SimpleProgram.tex

$ 
````
From this I infer that the problem is not the setting of $PATH, or at least not *just* the setting of $PATH.

Your mention of interpreted executables gave me an idea:  in Preferences, I pointed the Toolbox not to pdflatex but to a shell script which invokes pdflatex, but first writes some debugging code to a file in my directory tree.   When the Toolbox runs the script, and the script records the contents of /usr/bin, the contents are very unlike what I see when I look at /usr/bin from the shell.  Every file is shown as owned by my userid, rather than by root, and the contents of the directory differ: the contents overlap and neither set of programs is a subset of the other.  And -- of course -- pdflatex and pdftex are missing, in the /usr/bin seen by my shell script running from inside the Toolbox.

It looks as though the Flatpak version of TLA+ Toolbox is running in some kind of sandbox.  Wikipedia confirms that that is part of the *point* of Flatpak as a distribution method.  The problem is that the sandbox lacks any version of TeX.

So it looks as if I can either live without generating PDF from inside the Toolbox, or reinstall from a different source.

Thank you for your help.

**Comment by cmsmcq** [comment]
Just to confirm:  The problem I reported earlier today does not occur when running the version of the TLA+ Toolbox I just downloaded from Github.  So it appears to be an unfortunate property of the Flatpak version.

**Comment by ruthless-gunner** [comment]
Good man. I appreciate it.
