### ISSUE TITLE
SANY prints out confusing info about not finding module SpecTETraceDef in file SpecTETraceDef.tla

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#547]
**Version Info**

TLC version: 11/24/2020 nightly build
JRE version:  AdoptOpenJDK build 15.0.1+9
OS version: Windows 10

**What happened?**

I generated a TE spec with the latest nightly build where the SpecTETraceDef module is included in the SpecTE.tla file. If I run TLC on the generated SpecTE.tla file, SANY outputs the following noisy error:

```
File does not exist: C:\Users\ahelwer\downloads\cwdtlafailure\.\SpecTETraceDef.tla while looking in these directories: .\, jar:file:/C:/tools/tla/tools/nightly/2020-11-24/tla2tools.jar!/tla2sany\StandardModules\
```

SANY then finds SpecTETraceDef in the SpecTE.tla file and continues on its merry way.

**What did you expect to happen?**

I expected SANY to not report an error if it didn't encounter an error.

**Steps to reproduce**

 1. Use the latest (11/24) build to generate a TE spec with the `-generateSpecTE` flag
 2. Run TLC on the generated SpecTE.tla file, see SANY print error

**Comment by lemmy** [comment]
This is caused by the "monolith spec" feature introduced with 505e073ffe9b9eee8ebe4b375b2dad5f402fa36b and its adopted by the "trace evaluation" feature in d90d44389f98a72638127734b190266e342f2563.  The message indicates that TLC hasn't been able to find the module `SpecTETraceDef` in the file `SpecTETraceDef.tla` and falls back to looking for `SpecTETraceDef` in the monolith spec aka the root module.  It is not an error.

**Comment by ahelwer** [comment]
@lemmy this causes CI unit test failures; see https://travis-ci.org/github/tlaplus/tlaplus/builds/750276577

```
[junit] Running tlc2.TraceExplorationSpecTest
[junit] Tests run: 14, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 0.221 sec

BUILD FAILED
/home/travis/build/tlaplus/tlaplus/tlatools/org.lamport.tlatools/customBuild.xml:545: Test tlc2.TraceExplorationSpecTest failed
```

**Comment by pfeodrippe** [comment]
This can be closed o/
