### ISSUE TITLE
incorrect naming of subexpressions of operators defining recursive functions

### ISSUE THREAD

**Issue by zwergziege** [tlaplus/tlaplus#582]
Consider a function definition in the following form
```
f[s \in S] == ...
```
When referring to subexpressions of ```f``` the toolbox actually differentiates between recursive and non-recursive functions. If the function is non recursive it completely ignores the implied ```CHOOSE f: f = [s \in S |-> ...]``` and treats the ```...``` as the outermost expression (basically inserting ```!(f)!2```). This might be confusing if you stick to the spec, but is actually a reasonable decision because in most cases you want to use that expression.
If, however, the function is recursive, this is not the case anymore. In the resulting expression the ```CHOOSE``` part is no longer ignored (at least in some part of the code) but it doesn't seem quite right and something else must be going on. My guess is, that SANY still ignores it, but I'm quite new to TLA+ and could be wrong about anything here...

In the following theorems I always try to name the expression corresponding to ```...``` above. The interesting function is ```gc```. Either ```gc!(gc)!2!(n)``` or ```gc!(n)``` should yield the desired expression but the former gives an error (as expected if you ignore the ```CHOOSE``` part) and the latter expands to the equality of the chosen function where the function is replaced with ```n``` (as expected if you don't ignore the ```CHOOSE``` part), which is bogus in most cases...  
```
ga == [n \in Nat |-> n]
gb[n \in Nat] == n
gc[n \in Nat] == IF n = 0 THEN 0 ELSE 1+gc[n-1]
gd == CHOOSE gd: gd = [n \in Nat |-> IF n = 0 THEN 0 ELSE 1+gd[n-1]]

THEOREM \A n \in Nat: ga!(n) = n OBVIOUS \* TRUE
THEOREM \A n \in Nat: gb!(n) = n OBVIOUS \* TRUE
THEOREM gc!(0) = 0 OBVIOUS               \* FALSE (0 = [n \in Nat |-> IF n = 0 THEN 0 ELSE 1 + 0[n - 1]]) = 0
\*THEOREM gc!(gc)!2!(0) = 0 OBVIOUS      \* ERROR: Selecting subexpression of expression that has none.
THEOREM gc!(0) = gd!(0) OBVIOUS          \* TRUE
THEOREM gd!(gd)!2!(0) = 0 OBVIOUS        \* TRUE
```
I'm running toolbox 1.7.1

**Comment by xxyzzn** [comment]
It looks to me like in all cases, f[x \in S] == ... is being treated like

   f == [x \in S |-> ... ]

so f!(e) equals ...  with e substituted for x.  For a recursive
function, this is a syntactically illegal expression because it
contains f, which is undefined.  However, if you write f!(e)!...  you
can wind up with a syntactically correct expression.  Amusingly, the
value of gc!(0) does not depend on the value of the undefined
identifier gc.  So TLC and apparently TLAPS are able and willing to
deal with the expression.

So, one may not agree with what it does, but it appears that what it
does is consistent.  I happen to agree with what it does because this
is a purely syntactic construct.  From f = g you can't deduce that
f!1 = g!1.  So it's quite reasonable for its meaning with a function
definition construct to be consistent with its syntax, not with its
semantics.

I don't like the ! notation and I use it in only one place: to pick out a
subexpression for use in a TLC model.  I hope that someday it will
disappear from the language, but apparently that won't be soon.

**Comment by zwergziege** [comment]
> It looks to me like in all cases, f[x \in S] == ... is being treated like f == [x \in S |-> ... ]

i am quite positive, that this is in fact not the case. the comment on the theorem ```gc!(0) = 0``` is actually the obligation that TLAPS tries to prove. as stated above, this matches the case that ```CHOOSE``` is **not** ignored. if it was, the obligation would need to be true.

> Amusingly, the value of gc!(0) does not depend on the value of the undefined identifier gc.

if you mean that ```gc``` by then is defined by the operator of the same name, that is correct and corresponds to inserting ```!(gc)!2```. if you consider the 'usual' way ! works (and i'm not saying i prefer one way or the other), it does contain an unbound variable. ```IF n = 0 THEN 0 ELSE 1+gc[n-1]``` contains two free variables ```gc``` and ```n```. so one of them must still be, after we substitute 0 for the other. if ```CHOOSE``` is not ignored,  ```n``` is bound by the function definition, which seems to be the case for the reason above.

> I don't like the ! notation and I use it in only one place: to pick out a
> subexpression for use in a TLC model. I hope that someday it will
> disappear from the language, but apparently that won't be soon.

well, it is quite handy in proofs...

**Comment by xxyzzn** [comment]
I don't know what TLAPS does, since it does not use the SANY parser.  If its interpretation of ! is not consistent with SANY's, then it's a problem in TLAPS that should be reported.  

TLC does use the SANY parser and I have seen no reason to doubt that its interpretation of ! for a function definition is independent of whether or not the definition is recursive.   I was wrong when I wrote that f!...  could yield an expression containing an undefined symbol.  If it is written only where f is defined, as in a theorem containing f,  then the symbol f appearing in it is not undefined.  I have no idea what weird things can arise if you write f!... in the definition of f.  That's the problem with introducing a hack like !.   It would be useful to check whether doing so leads to an unsoundness in TLAPS.  Note that an f!... appears in the definition of f if f is defined with a RECURSIVE f, g, h  declaration and f! appears before the definition of  f, g, or h.  

I don't know what making ! "consistent with the semantics" means.   The semantics of TLA+ says that the definition is equivalent to a definition using a particular CHOOSE expression.  It is equivalent to lots of other definitions--for example

   IF TRUE THEN CHOOSE ... ELSE ...

Why should ! be defined in terms of any particular one of them?  The "operator" ! is not an operator.  It's a hack.   I would appreciate knowing what you find it useful for, if you could give very concise examples/explanations.  But privately, not on Github.

**Comment by zwergziege** [comment]
> I don't know what TLAPS does, since it does not use the SANY parser. If its interpretation of ! is not consistent with SANY's, then it's a problem in TLAPS that should be reported.

by reported you mean independently from this at the tlapm repo?

> I was wrong when I wrote that f!... could yield an expression containing an undefined symbol. If it is written only where f is defined, as in a theorem containing f, then the symbol f appearing in it is not undefined. 

why do you think so? that doesn't with my observations from the previous comment, that ```gc!(1)``` gives an error, saying that ```gc``` is not defined.

> I have no idea what weird things can arise if you write f!... in the definition of f.

as long as f is not defined RECURSIVE that should be illegal, since then f would not be a defined operator. else... well, formally speaking we'd have to prove gods existence to say stuff like 'god only knows'... but apparently SANY is more restrictive with ! than it is with operators since
```
RECURSIVE f
f == f!1
```
and 
```
RECURSIVE f
f == f
```

are similarly silly (as lamport would maybe say) but only the former is forbidden.

> I don't know what making ! "consistent with the semantics" means. The semantics of TLA+ says that the definition is equivalent to a definition using a particular CHOOSE expression. It is equivalent to lots of other definitions--for example
> 
> IF TRUE THEN CHOOSE ... ELSE ...
> 
> Why should ! be defined in terms of any particular one of them? The "operator" ! is not an operator. It's a hack.

sorry, the edit i made was quite rushed and i didn't give it the proper thought. if f!... uses the defined operator f to substitute for the implied CHOOSE the way these expressions are handled is of course correct. there still seems to be the issue that TLC uses an undefined symbol, but then i might have made some silly mistake. but as far as i know ```gc!(1)``` should work anywhere ```gc[1]``` works, right? shouldn't be too much of a deal though, since ! should only be used in proofs...

the original issue seems to be a problem with TLAPS exclusively.

**Comment by xxyzzn** [comment]
Sorry, I didn't notice that this is the TLAPS issues site.   

I'm glad to see that SANY does not allow f to be defined in terms of f! in either a recursive operator or recursive function definition.  I wonder if TLAPS does if it's used from the command line. 

I was wrong in saying that gc!(1) was undefined.  The fact that TLC produces an error when evaluating it seems at first glance to be a bug.  It is not important enough for me to give it a second glance.

**Comment by xxyzzn** [comment]
Ioannis Filippidis has confirmed that TLAPS and SANY/TLC treat f!... differently if f is defined by a recursive function definition. When f is defined by

   f[x \in S] == ...

the meaning of  f!e for some string e is defined by SANY/TLC in all cases and by TLAPS in the case that the definition is nonrecursve as if the definition of f were

    f  ==  [x \in S |-> ...]

If the definition is recursive, TLAPS treats f!e as if the definition of f were

   f == CHOOSE f : f = [x \in S |-> ...]

This discrepancy is not going to be fixed.

**Comment by zwergziege** [comment]
well that is lovely... diverging standards...

> This discrepancy is not going to be fixed.

because it is not a priority or because it is not even desired? (i.e. would a pr to either of the projects (preferably tlapm) be merged?)

**Comment by xxyzzn** [comment]
TLAPS is being implemented and maintained by a small group of people, most of whom spend most of their time doing other things.  There are more important improvements to TLAPS that have higher priority.  Too much time has already been spent on this problem, and I will not respond to any other comments on it.

**Comment by zwergziege** [comment]
i apologize for the inappropriate comment, i didn't want to be disrespectful and i respect the effort that is put into this project. this is why i asked whether or not a pull request would be accepted.

**Comment by muenchnerkindl** [comment]
If you want to fix this issue and prepare a pull request for tlapm, we would gladly consider it. Thank you for pointing out this discrepancy between SANY and the TLAPS parser (as well as issue #32 on the TLAPS repository).
