### ISSUE TITLE
Don't generate TTrace files by default

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#600]
In the latest version of TLC (`TLC2 Version 2.15 of Day Month 20?? (rev: d977051)`), when an invariant violation is found, it appears to generate `*_TTrace_*.{tla,cfg}` files in the current directory by default e.g.

```
-rw-r--r--@ 1 willyschultz  staff   105 Apr  2 11:11 mongo_raft_simple.cfg
-rw-r--r--@ 1 willyschultz  staff   841 Apr  2 11:14 mongo_raft_simple.tla
-rw-r--r--@ 1 willyschultz  staff   331 Apr  2 11:14 mongo_raft_simple_TTrace_1617376461.cfg
-rw-r--r--@ 1 willyschultz  staff  4345 Apr  2 11:14 mongo_raft_simple_TTrace_1617376461.tla
```
As I understand it, these files enable command line trace exploration. It seems to generate unexpected file clutter, though, and these generated files wouldn't naturally be ignored by a `.gitignore` pattern. It seems reasonable to turn off the generation of these files by default, and make it an opt-in feature, since presumably trace exploration from the command line is not necessarily meant to be used by casual users, but exists for [external tool support](https://github.com/alygin/vscode-tlaplus/issues/119), if I understand correctly. As a user, I found it jarring/unexpected when these files popped up without an obvious explanation. At present, I worked around it by using the `-noGenerateSpecTE` flag.

**Comment by lemmy** [comment]
@will62794 The reason why TLC generates the TTrace spec by default is that it is not possible to generate the TTrace spec after the fact (after TLC has terminated); one would have to re-run the potentially long-running model-checking.  The less technical reason is that a TTrace spec is the equivalent of the Toolbox's snapshot that lets one go back to an earlier stage of modeling (the original spec could be in-lined into TTrace spec).  Note that a trace spec is designed to be human-readable to bring trace expressions to the command line.  

What might alleviate your issue is the plan to in-line the `.cfg` in the TTrace spec and/or generate to a sub-directory such as `snaphots`.  Lastly, we could add e.g. an environment variable such as `TLC_NO_GEN_SPEC_TE` that turns it off (or on if the majority of users wants it off by default).

**Comment by will62794** [comment]
Yes, putting it in a sub-directory like `snapshots` (or even just in the existing `states` directory) seems better. My thinking was to disable it by default and just allow the `-generateSpecTE` flag to enable it for users that want it. In my opinion it would be better to disable it by default until there is a clearer sense that command line trace exploration is a widely used feature that benefits from default generation of these auxiliary files.

**Comment by lemmy** [comment]
With the shortened "-noTE" flag and minimizing the clutter by removing the config file (ed11002), I consider this addressed.
