### ISSUE TITLE
Bogus violation when checking liveness property [](FALSE ~> P)

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#604]
Originally report in http://discuss.tlapl.us/msg04237.html

```tla
------ MODULE Github604 ------
EXTENDS Naturals

VARIABLE x

Next == x' \in 0..3

Spec ==  x = 0 /\ [][Next]_x /\ WF_x(Next) \* F
====
```

For some fairness property `F`, and constant-level liveness properties with a state predicate `P` (`P` does not hold):

| Property | Rewritten To | Violation? | Bogus? | Comment |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| `<>TRUE` | `F /\ ~<>TRUE` | y | y | proved by TLAPS |
| `<>x \in Nat` | `F /\ ~<>(x \in Nat)` | n | n | state-level |
| `<>[]TRUE` | `F /\ ~<>[]TRUE` | n | n |
| `<>FALSE` | `F /\ ~<>FALSE` | y | n |
| `<>[]FALSE` | `F /\ ~<>[]FALSE` | y | n |
| `[](TRUE=><>P)` | `F /\ ~[](~TRUE \/ <>P)` | n | n |
| `TRUE~>P` | `F /\ ~[](~TRUE \/ <>P)` | n | n |
| `[](FALSE=><>P)` | `F /\ ~[](~FALSE \/ <>P)` | y | y |
| `FALSE~>P` | `F /\ ~[](~FALSE \/ <>P)` | y | y |
| `FALSE~>FALSE` | `F /\ ~[](~FALSE \/ <>FALSE)` | y | y |
| `FALSE~>TRUE` | `F /\ ~[](~FALSE \/ <>TRUE)` | y | y |
| `TRUE~>FALSE` | `F /\ ~[](~TRUE \/ <>FALSE)` | y | n |
| `TRUE~>TRUE` | `F /\ ~[](~TRUE \/ <>TRUE)` | n | n |

"Rewritten To" in `tlc2.tool.liveness.Liveness.processLiveness(ITool)` applying https://en.wikipedia.org/wiki/Material_implication_(rule_of_inference) in case of leads-to.

Note: A constant-level invariant such as `TRUE`, TLC happily checks the specification without raising a warning.  An invariant `[]TRUE` is level-checked as temporal formula and, thus, reject by TLC with `Error: The invariant Inv is not a state predicate (one with no primes or temporal operators).`.

Related: https://github.com/tlaplus/tlaplus/issues/302

**Comment by Isaac-DeFrain** [comment]
The ~> operator seems to work as expected with some state predicates and not others.

For context, I am writing a specification of a handshaking protocol [here](https://github.com/tezedge/model-p2p/blob/handshaking/handshaking/blacklist_timeouts/Handshaking.tla). After exchanging some messages in a specific order, nodes form a "connection". A property I want the protocol to satisfy is:

OnceConnectedAlwaysConnected ==
    \A g, h \in GOOD_NODES :
        LET connected == g \in connections[h] /\ h \in connections[g] IN
        connected ~> []connected

~> works exactly as expected for this property.

Among the messages that are sent, the last one is an "ack". I want to verify that the first receiver of an ack message always responds to it with an ack message or eventually blacklists the sender, i.e.:

GoodNodesAlwaysRespondToAckMessagesOrBlacklist ==
    \A g, h \in GOOD_NODES :
        /\ ack_msg(h) \in messages[g]
        /\ h \notin sent_ack[g] ~>
            \/ ack_msg(g) \in messages[h]
            \/ h \in blacklist[g]

A bogus error trace is provided as a counterexample to this property (irrelevant details have been omitted):

Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
/\ blacklist = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = (0 :> {} @@ 1 :> {} @@ 2 :> {})

State 2: <BadNodeSendsGoodNodeMessage line 245, col 9 to line 247, col 124 of module Handshaking>
/\ blacklist = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = (0 :> {} @@ 1 :> {[from |-> 0, type |-> "bad"]} @@ 2 :> {})

State 3: <InitiateConnection line 93, col 5 to line 105, col 26 of module Handshaking>
/\ blacklist = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = (0 :> {} @@ 1 :> {[from |-> 0, type |-> "bad"]} @@ 2 :> {})

State 4: <Timeout line 250, col 5 to line 250, col 52 of module Handshaking>
/\ blacklist = (0 :> {} @@ 1 :> {} @@ 2 :> {0})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = (0 :> {} @@ 1 :> {[from |-> 0, type |-> "bad"]} @@ 2 :> {})

State 5: <InitiateConnection line 93, col 5 to line 105, col 26 of module Handshaking>
/\ blacklist = (0 :> {} @@ 1 :> {} @@ 2 :> {0})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = ( 0 :> {} @@
  1 :> {[from |-> 0, type |-> "bad"]} @@
  2 :> {[from |-> 1, type |-> "conn"]} )

State 6: <Timeout line 250, col 5 to line 250, col 52 of module Handshaking>
/\ blacklist = (0 :> {} @@ 1 :> {2} @@ 2 :> {0})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = ( 0 :> {} @@
  1 :> {[from |-> 0, type |-> "bad"]} @@
  2 :> {[from |-> 1, type |-> "conn"]} )

State 7: <HandleBad line 218, col 8 to line 219, col 51 of module Handshaking>
/\ blacklist = (0 :> {} @@ 1 :> {0, 2} @@ 2 :> {0})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = (0 :> {} @@ 1 :> {} @@ 2 :> {[from |-> 1, type |-> "conn"]})

State 8: <RespondToConnectionMessage line 108, col 5 to line 126, col 47 of module Handshaking>
/\ blacklist = (0 :> {} @@ 1 :> {0, 2} @@ 2 :> {0})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = (0 :> {} @@ 1 :> {} @@ 2 :> {})

State 9: <Timeout line 250, col 5 to line 250, col 52 of module Handshaking>
/\ blacklist = (0 :> {} @@ 1 :> {0, 2} @@ 2 :> {0, 1})
/\ sent_ack = (0 :> {} @@ 1 :> {} @@ 2 :> {})
/\ messages = (0 :> {} @@ 1 :> {} @@ 2 :> {})

State 10: Stuttering

Note: an ack message is never sent in this execution.

**Comment by lemmy** [comment]
@Isaac-DeFrain Could you try to minimize/simplify the spec?  What about the spec's other liveness properties?

**Comment by Isaac-DeFrain** [comment]
Yes. What I am noticing is that TLC seems to generate bogus counterexamples for properties of the form P ~> Q and checks correctly for properties of the form P ~> []Q where P and Q are state predicates. I'm still investigating and will provide a much simpler spec demonstrating this.

**Comment by lemmy** [comment]
Please provide a simpler spec.  The upcoming fix for the original issue, related to incorrect handling of constant-level sub-expression where users usually write state-level expressions, doesn't appear relevant for your case.

**Comment by lemmy** [comment]
@Isaac-DeFrain Please also check if [earlier versions of TLC produce](https://tla.msr-inria.inria.fr/tlatoolbox/branches/) a correct counterexample.

**Comment by lemmy** [comment]
@Isaac-DeFrain Have you been able to come up with a simplified spec?

**Comment by Isaac-DeFrain** [comment]
@lemmy In the process of writing a simplified spec, I realized that I was making an error in how I was expressing the property. For example, I wrote something like:
/\ A
/\ B ~>
  /\ C
  /\ D
which is equivalent to A /\ (B ~> C /\ D). However, what I intended to express was (A /\ B) ~> (C /\ D). The "bogus errors" I was seeing where 100% caused by my incorrect expression of my intention. I can confirm that all properties work as expected after I made this change.

**Comment by Calvin-L** [comment]
I spent an hour looking into this. I have a hypothesis about the cause, although my understanding of TLC's liveness-checking code is very sketchy.

The problem goes away if you change [this line](https://github.com/tlaplus/tlaplus/blob/ab14a33e39c78e4c88e81b664b9a8c916b943cab/tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/TBGraphNode.java#L42) in TBGraphNode's constructor. Replace:

    if (ln instanceof LNState) {

with

    if (ln instanceof LNState || ln instanceof LNBool) {

----

I'll try to explain why I think that line might be significant. Here's the spec I'm using:

```
---- MODULE LeadsTo ----

EXTENDS Naturals

VARIABLE x

Init == x = 0

Inc ==
    /\ x < 5
    /\ x' = x + 1

Reset ==
    /\ x' = 0

Next ==
    \/ Inc
    \/ Reset

Property ==
   [](TRUE \/ <>(x=3)) \* <---- the property to check, equivalent to (FALSE ~> (x=3))

====
```

TLC proves the property by trying to satisfy the property's negation. So, it starts from

    ~[](TRUE \/ <>(x=3))

Simplification converts this to:

    <>FALSE

The TBGraphNode constructor _ignores_ the `FALSE` constant, since it is only looking for state expressions. Somehow this causes the tableau-based prover to give erroneous results. Including `FALSE` in the set of notable state expressions fixes the problem.

An alternative fix might be to improve the simplifier to convert `<>FALSE` to `FALSE`...  Although, my intuition says that the liveness checking code should work even if fed boolean constants, and the simplification is just an optimization. Or, put another way: the simplifier's contract is that it produces logically-equivalent expressions. The liveness checker's contract is that it produces correct output on any input it accepts. (Although, I'm prepared to accept that TLC's design philosophy could be different from my intuition.)

**Comment by lemmy** [comment]
@Calvin-L Great, we came to the same conclusion: https://github.com/lemmy/tlaplus/commit/462c2c891609ab57e1313fa2cae8b22618f607f6#diff-f996d325dd68aa45c6ad7c13094052819b4ba3e92f661c9e846e87d5ed083a05L42-L51
