### ISSUE TITLE
(Obsolete) TLC!Any operator causes error

### ISSUE THREAD

**Issue by anton-trunov** [tlaplus/tlaplus#663]
TLC does not seem to be able to handle updating a variable with a function. Here is a minimised example coming from a transpiler:

```tla
----- MODULE Repro -----

EXTENDS TLC

VARIABLES func

Next ==
  func' = [x \in Any |-> x]

Init == func = 0

=====
```

This fails with

```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.RuntimeException
: util.Assert$TLCRuntimeException: Attempted to compute the number of elements in the overridden value ANY.
The error occurred when TLC was evaluating the nested
expressions at the following positions:
    The error call stack is empty.
```

Maybe there is a workaround?

**Comment by lemmy** [comment]
This is because of the use of `Any`, whose use is discouraged (section "Any" in [current-tools.pdf](https://lamport.azurewebsites.net/tla/current-tools.pdf)).

**Comment by anton-trunov** [comment]
Thanks for your quick reply! Unfortunately, using `Any` in my case is on purpose -- without it, I either get a huge performance penalty (this is what my experiments tell me), or I need a placeholder to fix the impedance mismatch between System F and set theory.

**Comment by lemmy** [comment]
You would probably end up playing whack a mole when trying to fix the problems in TLC with `Any`.  Since there seems to be [somebody else](https://groups.google.com/g/tlaplus/c/4z08fIXSrRI/m/gQOuxV69BQAJ) mapping a typed programming language to TLA+, it's perhaps best to investigate and identify the general pattern, and then look for a solution to the performance problem.

**Comment by anton-trunov** [comment]
Thanks for the pointer, that would be indeed useful.
