### ISSUE TITLE
Simulation on TLA+ Toolbox never ends

### ISSUE THREAD

**Issue by jonesmartins** [tlaplus/tlaplus#703]
When running simulations on both the current and nightly versions of the Toolbox, the simulation never ends. 

When stopped, it says "states found: <any value> | distinct states: 1"

**Comment by lemmy** [comment]
Simulation is a stateless, random exploration of the state graph.  By design, the simulation never stops unless killed or an upper bound for the number of traces is given to TLC at startup.

"In simulation mode, TLC does not try to examine all reachable states.  Instead, it checks an unending series of behaviors, each of which it constructs by starting from a randomly choosen initial state and repeatedly making a random choice of a possible next state.  (In this mode, you stop TLC by clicking the  Cancel  button on the dialog that the Toolbox pops up when it runs TLC.)  You specify the maximum length of each behavior that it generates.  If you want to know what specifying the Seed and Aril does, look them up in Specifying Systems.  When run in simulation mode, the only statistics TLC reports are for States Found." (https://tla.msr-inria.inria.fr/tlatoolbox/doc/model/tlc-options-page.html)

**Comment by jonesmartins** [comment]
Hi, Markus. Shouldn't the simulation stop if I specify a maximum length?

**Comment by lemmy** [comment]
The length gives the upper bound of the length of every behavior in the unending series of behaviors generated by the simulator.  Only the number of traces turns the unending series into a finite series.

**Comment by jonesmartins** [comment]
I believe I made a mistake, but let me confirm it with you first.

I tried simulating this HourClock.tla with max. number of traces = 10 and max. length of trace = 10.
```tla
---------------------- MODULE HourClock ----------------------
EXTENDS Naturals
VARIABLE hr
HCini  ==  hr \in (1 .. 12)
HCnxt  ==  hr' = IF hr # 12 THEN hr + 1 ELSE 1
HC  ==  HCini /\ [][HCnxt]_hr /\ WF_hr(HCnxt)
--------------------------------------------------------------
THEOREM  HC => []HCini
==============================================================
```
The simulation finished, as expected, resulting in this:
![image](https://user-images.githubusercontent.com/15959626/147280376-24987b40-46b8-49c4-bb9c-0497c0b44f45.png)

Is this behavior correct? 

Also, should the Toolbox generate a Spec_actions.dot file after the simulation ends?

**Comment by lemmy** [comment]
Yes, you will see 10 traces and 112 states found if you switch to a single worker.  Also, progress shows 412 instead of 400 states because it includes the number of initial states.

Except the warning (yellow highlight) about `HCnxt` being uncovered should be corrected.

**Comment by jonesmartins** [comment]
> Yes, you will see 10 traces and 112 states found if you switch to a single worker. 

I changed to 2 and I did see the difference. I couldn't try with 1 worker, though.

![image](https://user-images.githubusercontent.com/15959626/147283655-66ab62fb-30f7-4782-a336-0ca5189f8471.png)

Results:

![image](https://user-images.githubusercontent.com/15959626/147283701-155586be-bf2a-4441-93c7-bc83d32dae1a.png)

**Comment by lemmy** [comment]
Are you saying that the buttons on the spinner (`+`/`-`) are disabled?  If yes, please describe your environment (OS, Toolbox, ...).

**Comment by jonesmartins** [comment]
Yes, they are disabled.

Toolbox and tla2tools: Nightly version download on 2021-12-20.
OS: Ubuntu 20.04.3 LTS 64-bit
