### ISSUE TITLE
INSTANCE: Constant declared as `C(_)`, is substituted with operator `C(_, _)` without error or warning

### ISSUE THREAD

**Issue by craft095** [tlaplus/tlaplus#723]
Constant declared as `C(_)`, is substituted with operator `C(_, _)` without error or warning:

```
---- MODULE Task0 ----

EXTENDS Naturals

---- MODULE Inner ----
CONSTANT C(_)

D(x) == C(x)
====

C(x, y) == x

INSTANCE Inner

VARIABLE x
Spec == x = 0 /\ [][x' = D(x)]_x
Inv == x = 0

====
```

**Comment by lemmy** [comment]
@ahelwer, during yesterday’s TLA+ community call, you mentioned a specific SANY behavior related to operator overloading. Could you please clarify if the behaviors described by the issue is the one you were referring to?

**Comment by ahelwer** [comment]
Here are the operator overloading warning cases:

https://github.com/tlaplus/tlaplus/blob/a52b3c47ac87cbcd76a1f91a1ac0f767055e8e60/tlatools/org.lamport.tlatools/test/tla2sany/semantic/error_corpus/W4800_Test.tla#L1-L5
https://github.com/tlaplus/tlaplus/blob/a52b3c47ac87cbcd76a1f91a1ac0f767055e8e60/tlatools/org.lamport.tlatools/test/tla2sany/semantic/error_corpus/W4800_Extended.tla#L1-L5
https://github.com/tlaplus/tlaplus/blob/a52b3c47ac87cbcd76a1f91a1ac0f767055e8e60/tlatools/org.lamport.tlatools/test/tla2sany/semantic/error_corpus/W4801_Instance_Test.tla#L1-L10
https://github.com/tlaplus/tlaplus/blob/a52b3c47ac87cbcd76a1f91a1ac0f767055e8e60/tlatools/org.lamport.tlatools/test/tla2sany/semantic/error_corpus/W4801_Test.tla#L1-L7

This actually is a bit counter-intuitive behavior since operator overloading in other dynamic languages works like "last defined wins" but here TLA+ uses "first defined wins".

There is a closely related error when the overloaded definitions are of different "kinds" (operators vs. constants vs. variables, etc.):

https://github.com/tlaplus/tlaplus/blob/a52b3c47ac87cbcd76a1f91a1ac0f767055e8e60/tlatools/org.lamport.tlatools/test/tla2sany/semantic/error_corpus/E4224_Test.tla#L1-L5
https://github.com/tlaplus/tlaplus/blob/a52b3c47ac87cbcd76a1f91a1ac0f767055e8e60/tlatools/org.lamport.tlatools/test/tla2sany/semantic/error_corpus/E4224_Extended.tla#L1-L5

**Comment by lemmy** [comment]
> This actually is a bit counter-intuitive behavior since operator overloading in other dynamic languages works like "last defined wins" but here TLA+ uses "first defined wins".
> 
> There is a closely related error when the overloaded definitions are of different "kinds" (operators vs. constants vs. variables, etc.):

I would argue that the comparison with operator overloading in other languages is somewhat misleading. Those languages intentionally define overloading as a language feature. TLA+, by contrast, does not support operator overloading at all; in fact, "_There is no overloading of operators in TLA+_" (from page 2 of https://lamport.azurewebsites.net/pubs/high-level.pdf). TLC’s behavior in the presence of multiple definitions should therefore not be understood as a form of overloading with a “first defined wins” rule. Rather, it is better viewed as recovery from a naming conflict: TLC happens to proceed using the first definition it encounters and emits a warning, but that behavior is a tool-level tolerance mechanism, not a language feature.

**Comment by ahelwer** [comment]
Hmm, well this is encoded & checked at the SANY level (now reified and given a "standard" error code) so I guess the question of whether this is a language feature or a tool feature is a bit iffy. SANY could be pretty easily changed to make this an error instead of a warning. Possibly a question for the Specification Language Committee?
