### ISSUE TITLE
Toolbox unusable with UHD display under Windows

### ISSUE THREAD

**Issue by Monte-Christo** [tlaplus/tlaplus#78]
On 4K displays, the toolbox model checker window looks like this:
![image](https://user-images.githubusercontent.com/8224318/31036001-98eca400-a56a-11e7-851d-bf70d751bcae.png)

Another example:
![image](https://user-images.githubusercontent.com/8224318/31036075-fc87d0a2-a56a-11e7-90b3-06a15137cfcf.png)

And one more:
![image](https://user-images.githubusercontent.com/8224318/31036116-33aa0992-a56b-11e7-8472-117aa9b79708.png)

The tiny icons and text make the toolbox almost unusable on such displays.

**Comment by lemmy** [comment]
Related to https://github.com/tlaplus/tlaplus/issues/49

**Comment by Monte-Christo** [comment]
This ought be labelled as a **bug**, not an enhancement. Usability is very poor; one has to use the screen magnifier to see anything at all.

**Comment by quaeler** [comment]
Likely related to [Eclipse 421383](https://bugs.eclipse.org/bugs/show_bug.cgi?id=421383) (marked resolved fixed in 4.5 which is the version that the Toolbox (at least 1.5.3) derives from, but the comments through last month indicate people still having problems even under 4.7)

From your screenshots @Monte-Christo i'm assuming you're on Windows 10?

**Comment by Monte-Christo** [comment]
Correct, Win 10 Pro, 64-bit.

**Comment by lemmy** [comment]
[Eclipse Photon](https://www.eclipse.org/eclipse/news/4.8/) might take care of the most serious issues.

**Comment by quaeler** [comment]
as agreed with mku in email, there are no specific outstanding issues keeping this open, so i am closing it.
