### ISSUE TITLE
TLC `-Dtlc2.TLC.stopAfter` timer does not start until actual model checking

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#788]
## Description
Some specs take an extremely long time to start up, for example if their constant operators generate enormous sets. One example of this is https://github.com/tlaplus/Examples/tree/master/specifications/CarTalkPuzzle/CarTalkPuzzle.toolbox/Model_3. In this case, TLC will ignore the `-Dtlc2.TLC.stopAfter` setting, since it seemingly only starts the timer once model checking proper starts. I was hoping to use this parameter to smoke-test large models in the tlaplus/examples repo, seeing whether they immediately error or anything. Other observations:

- The timer also doesn't restrict liveness checking I think?
- The timer also doesn't start until after the set of initial states are computed?

## Expected Behavior
The `-Dtlc2.TLC.stopAfter` setting should encompass all operations performed by TLC, not just model-checking itself.

## Actual Behavior
TLC runs for a very long time, seemingly trying to generate an enormous set before starting model-checking.

## Steps to Reproduce
1. Clone tlaplus/examples repo
2. To see how timeout doesn't restrict constant set generation time, run `java -Dtlc2.TLC.stopAfter=5 -cp tla2tools.jar tlc2.TLC specifications/CarTalkPuzzle/CarTalkPuzzle.toolbox/Model_3/MC`
3. To see how timeout doesn't restrict initial state generation, run `java -Dtlc2.TLC.stopAfter=5 -cp tla2tools.jar tlc2.TLC specifications/EinsteinRiddle/Einstein`
4. To see how timeout doesn't restrict liveness checking, run `java -Dtlc2.TLC.stopAfter=5 -cp tla2tools.jar tlc2.TLC specifications/CoffeeCan/CoffeeCan -config specifications/CoffeeCan/CoffeeCan1000Beans.cfg`

## Steps Taken to Fix
TLC can be pre-empted with SIGINT, and this can be recognized by checking that the error code [is 130](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html) in bash.

## Possible Fix
Pre-empt TLC during initial constant set generation if a timeout occurs.

## Your Environment
 - TLC version: TLC2 Version 2.18 of Day Month 20?? (rev: ad45483)
 - Operating System: Arch Linux

**Comment by Calvin-L** [comment]
I could also benefit from this, but I am... wary.
 - It doesn't look like this was ever intended to be a user-facing feature (it is an undocumented system property, not a real command-line argument). Is this something we really want to make into a real feature? What should TLC actually do when it runs out of time? We would have to define this precisely.
 - In general, polite timeouts are incredibly difficult to support (long brain dump below).
 - The impolite [timeout](https://linux.die.net/man/1/timeout) command already exists.

----

I spent a long time implementing [a timeout feature in a previous project](https://github.com/CozySynthesizer/cozy/blob/56b4434/cozy/main.py#L38). It's darn hard!

There are _polite_ timeouts that allow the application to shut down gracefully and _impolite_ timeouts that do not. If we supported this feature, we obviously want a polite timeout; your operating system already offers an ideal [impolite timeout mechanism](https://linux.die.net/man/1/timeout) using signals (as you mentioned). A polite timeout would give TLC a chance to output something meaningful and write well-formed data to disk, which enables features like `-recover`.

However, polite timeouts come with a huge bag of caveats. The simplest and least-error-prone way to implement them is to have every thread periodically check if timeout has happened. If you come up with a better method please let me know, but until then:

**Polite timeouts complicate the code.** Anywhere TLC would do a significant amount of work it would have to check for timeout occasionally. That means, for instance, that we can't use the standard library sort routines, since there is no way to interrupt them on timeout! We would have to implement our own sort routines that periodically check for timeout. What a mess! This applies to _every_ method in TLC and its dependencies.

**Polite timeouts can slow down the program.** While the performance penalty can be mitigated, it is quite hard to find a way to implement polite timeouts such that the periodic checking doesn't slow down the whole system. You have to do _enough_ work between checks that the checks themselves contribute a negligible total to the program's runtime. This is especially difficult in recursive algorithms like TLC's expression evaluator, where a recursive call might do a small amount of work or an enormous amount.

**Polite timeouts are hard to test.** Any test that really checks the timeout will have to be slow and flaky. Slow because it checks a real-time property, and thus the test _cannot_ run faster than perhaps a few seconds. Flaky because polite timeouts have to be best-effort, so the test will sometimes fail if you get unlucky with the scheduler. For instance, if the system is under heavy load then TLC may take much longer than the requested timeout.

**Polite timeouts are easily ignored in new features.** If we implement this today, every new feature will have to care about it. For instance, I want to add support for `\EE` to TLC; if I do, I will certainly forget that my code has to periodically check for timeout, and so the timeout feature will probably erode a little with each other feature we add.

**Comment by ahelwer** [comment]
Speaking of polite vs. impolite timeouts, I actually encountered an error (sadly output above my terminal history threshold) when this timeout triggered while TLC was evaluating a java module override during model checking. It resulted in an uncaught exception.

**Comment by lemmy** [comment]
> I could also benefit from this, but I am... wary.

@Calvin-L `TLCGet("exit", expr)` at the level of the next-state relation or in a state constraint has more predictable behavior (example at https://github.com/microsoft/CCF/blob/1f7c73a4d49815941b60cfecbe5d5705707d97a2/tla/SIMccfraft.tla#L43-L47).
