### ISSUE TITLE
LazyValue can cause TLC to generate too many or too few states

### ISSUE THREAD

**Issue by ybbh** [tlaplus/tlaplus#798]
## Description

The model checker generated empty states which did not meet expectations.
I wrote a simple TLA+ specfication, https://github.com/ybbh/tla_state.
When I used the model checker to check it, it generated empty initial states.

## Expected Behavior

Model checker should generate non-empty initial states.

## Actual Behavior

Model checker generated empty initial states.

## Steps to Reproduce
1. git clone git@github.com:ybbh/tla_state.git
2. Toolbox: File -> Open Spec -> Add New Spec -> open state.tla
3. Toolbox: models -> New Model -> filling Temporal formula with **Spec** -> setting constants NODE_ID by **{"n1", "n2"}**
4. Toolbox: Run TLA on the model
5. Toolbox: The model checker result generated empty initial states
![result](https://github.com/ybbh/tla_state/blob/main/figures/node_2.png)

## Steps Taken to Fix

1. When I changed the constants NODE_ID by **{"n1"}**, it generated correct result.

2. The initial states would be OK if I uncomment this line in [state.tla](https://github.com/ybbh/tla_state/blob/main/state.tla).
  
    ```
      __WhyWeNeedThis == S2
    ```

## Possible Fix

Possible when producing the initial state, the model checker threw some unknown exceptions.

## Your Environment

 - TLC version: 2.15, 2.16
 - version: 1.8.0.202303090234, 1.7.1.202012311918
 - Operating System: Windows 10

**Comment by lemmy** [comment]
Minimized test case:

```tla
--------------------------------- MODULE state ---------------------------------
EXTENDS common

CONSTANT S

VARIABLE x, y

vars == <<x, y>>

Init ==
    Indirect(S, x, y)
 
\* __WhyWeNeedThis == S2
   
Spec == 
    /\ Init 
    /\ [][UNCHANGED vars]_vars

===============================================================================
------------------------------ MODULE common ------------------------------
S1 == "S1"
S2 == "SomeRandomString"

Direct(S, xx, yy) ==
    /\ xx \in [S -> {"S1","S2"}]
    /\ yy \in [S -> S]
    /\ \A s \in S : 
        xx[s] = "S1" => yy[s] = s

Indirect(S, xx, yy) == 
    Direct(S, xx, yy)
    
=============================================================================
```

```
SPECIFICATION
    Spec
CONSTANT
    n1 = n1
    n2 = n2 
    S = {n1, n2}
```

* Replacing {"S1","S2"} with {1,2} makes no difference
* Replacing `Indirect` with `Direct` in `Init` changes the number of distinct states to nine

**Comment by lemmy** [comment]
This problem justifies the release of a new version of TLC. At present, my inclination is to disable LazyValue entirely due to the issues it has already caused and its uncertain performance benefits. Performance tests are currently being run to establish a baseline, followed by a run with LV turned off.
@Calvin-L Any thoughts?

**Comment by lemmy** [comment]
Commit a323460 addresses this bug *without* disabling `LazyValue`.

**Comment by Calvin-L** [comment]
> At present, my inclination is to disable LazyValue entirely

I'm tentatively in favor.

For what it's worth, I have always found the design of LazyValue to be a little worrisome. LazyValue does not act like other values; _callers_ are responsible for checking if a value is a LazyValue and reading (and _writing_!) the cached value appropriately. Does TLC check for LazyValue in all the places it has to? Are there any points where it can flow into unexpected places? In this issue we found one such point (LazyValue can flow into other LazyValues, in a sense). Are there more? I don't know a simple way to find out.

So, disabling it seems good since it is simple (unlike finding other LazyValue bugs) and not very risky (unlike doing a big refactor to redesign LazyValue).

> uncertain performance benefits

A lot of knowledge about this seems to be locked up in brains (yours? Simon's? someone else?) rather than written down. If I understand correctly:

TLC would like to have the similar performance characteristics as a "normal" call-by-value functional programming language. So if I write `F(x)`, I can expect that `x` will be simplified only once, and then the simplified value can be re-used while TLC is working on the body of `F`.

However, because `x` may appear under a temporal operator inside F (e.g. if `F(x) == ENABLED (x' = 0)`), it would be wrong for TLC to always fully simplify arguments before evaluating the body.

LazyValue is a kind of compromise, where the value of `x` is cached as long as it does not appear inside certain temporal operators (which is normally true). If that's right, then I think I see how to construct cruel inputs that force TLC to do an exponential amount of work if we disable LazyValue entirely. On the other hand, I am not sure I've ever written a spec that does such a thing.

Perhaps, if nobody has done so already, we need to think more carefully about when TLC can act like a call-by-value evaluator and when it can't. The right set of rules might make the performance problem very easy to solve for 99.99% of cases.

**Comment by lemmy** [comment]
> A lot of knowledge about this seems to be locked up in brains (yours? Simon's? someone else?) rather than written down.
> [...]
> On the other hand, I am not sure I've ever written a spec that does such a thing.

It appears that this knowledge predates the "second generation" of TLC developers (which includes us). The only information I have is that I haven't seen a real-world specification that exhibits an exponential amount of work when LazyValue is disabled. Based on this, I am inclined to change LazyValue to be disabled by default, but leave an option for users to reenable via a Java System Property. If a significant number of users complain about performance degradation, we can consider redesigning LazyValue at that point.  

If they are negligible, I would propose that we still merge https://github.com/tlaplus/tlaplus/pull/799 to prevent users who opt to re-enable LazyValue from running into this particular LazyValue bug.

**Comment by lemmy** [comment]
> If they are negligible, I would propose that we still merge #799 to prevent users who opt to re-enable LazyValue from running into this particular LazyValue bug.

https://github.com/tlaplus/tlaplus/pull/799 will now be optimized out of LazyValue caching is disabled.  It can later be flipped if caching becomes off by default. 

```diff
diff --git a/tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SymbolNodeValueLookupProvider.java b/tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SymbolNodeValueLookupProvider.java
index e56b9b850..9987bbb8d 100644
--- a/tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SymbolNodeValueLookupProvider.java
+++ b/tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SymbolNodeValueLookupProvider.java
@@ -87,7 +87,7 @@ public interface SymbolNodeValueLookupProvider {
        }

        default Object getVal(final ExprOrOpArgNode expr, final Context c, final boolean cachable, final CostModel cm, final int forToolId) {
-               if (!LazyValue.LAZYEVAL_OFF && expr instanceof OpApplNode) {
+               if (LazyValue.LAZYEVAL_ON && expr instanceof OpApplNode) {
                        final OpApplNode oan = (OpApplNode) expr;
                        // Do not create a LazyValue that "points to" another LazyValue.
                        // Related:
diff --git a/tlatools/org.lamport.tlatools/src/tlc2/value/impl/LazyValue.java b/tlatools/org.lamport.tlatools/src/tlc2/value/impl/LazyValue.java
index 5dbdbd3c3..370859e41 100644
--- a/tlatools/org.lamport.tlatools/src/tlc2/value/impl/LazyValue.java
+++ b/tlatools/org.lamport.tlatools/src/tlc2/value/impl/LazyValue.java
@@ -32,12 +32,12 @@ public class LazyValue extends Value {
         * bug where TLC generates and incorrect set of states with certain statements.
         * More details can be found at https://github.com/tlaplus/tlaplus/issues/113.
         */
-       public static final boolean LAZYEVAL_OFF = Boolean.getBoolean(tlc2.value.impl.LazyValue.class.getName() + ".off");
+       public static final boolean LAZYEVAL_ON = Boolean.getBoolean(tlc2.value.impl.LazyValue.class.getName() + ".on");

        static {
                // Indicate if LazyValue will be disabled in this TLC run.
-               if (LAZYEVAL_OFF) {
-                       ToolIO.out.println("LazyValue is disabled.");
+               if (LAZYEVAL_ON) {
+                       ToolIO.out.println("LazyValue is enabled.");
                }
        }
   /**
@@ -63,7 +63,7 @@ public class LazyValue extends Value {
     this.val = null;
     // See comment on cachable's meager performance in Tool.java on line 1408.
     // See other note about a bug that surfaced with LazyValue in Tool.java on line ~1385.
-    if (LAZYEVAL_OFF || !cachable) {
+    if (LAZYEVAL_ON || !cachable) {
        this.val = UndefValue.ValUndef;
     }
   }
```

**Comment by lemmy** [comment]
Hypothesis: The correct "cached" value for `x` should be stored in the partially constructed `TLCState` when `Tool.java` backtracks.

**Comment by lemmy** [comment]
This will soon go out to the TLA+ google group.  Anything to add?

---

"Important TLC Bugfix: Upgrade to TLC 1.7.3 Recommended"

A rare yet severe bug in TLC has been identified and resolved. This bug was present in the initial implementation of TLC and could have led to the generation of incorrect initial states or an inaccurate set of potential next states when evaluating a state. Either issue might have resulted in TLC not examining all accessible states. Technical details can be found at https://github.com/tlaplus/tlaplus/issues/798.

Users can verify if they have been affected by the bug by running TLC with the Java system property `-Dtlc2.value.impl.LazyValue.off=true` and observing whether the number of initial and distinct states changes. However, please note that disabling LazyValue may lead to significant performance degradation.

We strongly recommend all users to upgrade to the TLC 1.7.3 maintenance release, available at https://github.com/tlaplus/tlaplus/releases/tag/v1.7.3. Regrettably, we are unable to provide Toolbox maintenance releases. Instead, we advise users to switch to the latest 1.8.0 build, accessible at https://github.com/tlaplus/tlaplus/releases/tag/v1.8.0. In addition, the most recent TLA+ VSCode nightly build, which includes the bugfix, can be found at https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus-nightly.

**Comment by Calvin-L** [comment]
No, that sounds like a good summary to me! ⛵
