### ISSUE TITLE
Retire bare-metal performance tests

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#864]
The [performance tests](https://github.com/tlaplus/tlaplus/blob/master/.github/workflows/perf.yml), which are currently executed on a sponsored Equinix bare-metal machine, will need to be discontinued. This is due to the termination of Equinix's sponsorship, leaving us without a replacement machine to run these tests.   They ran on a reserved bare-metal machine to make sure that results are comparable.

**Comment by lemmy** [comment]
Workflow has been disabled, and the Equinix resource including the project have been deleted.

**Comment by lemmy** [comment]
Note to self: Delete the TLA+ organization once Equinix as done the final invoicing.

**Comment by lemmy** [comment]
Org has been deleted

**Comment by lemmy** [comment]
FWIW, I explored some alternatives:

* Although it provides exclusive access to the hardware (less noise), self-hosting a GitHub runner on a local machine is unstable due to network issues.
* The [standard GitHub-hosted runners](https://docs.github.com/en/enterprise-cloud@latest/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) lack sufficient disk space to run the performance benchmarks, which require about 10GB during execution.
* [Larger GitHub runners](https://docs.github.com/en/enterprise-cloud@latest/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#specifications-for-general-larger-runners) offer adequate disk space but are not available with our free GitHub tier. Upgrading to the [Teams tier](https://github.com/pricing) would cost $4 per month, in addition to the compute minutes.

**Comment by ahelwer** [comment]
I have $150/month in persistent Azure credits (I think you probably should too?) which we can use to set up a persistent VM for this purpose.

**Comment by lemmy** [comment]
It's more reliable if the infrastructure doesn't rely on individual subscriptions. In my opinion, the TLA+ Foundation should cover this cost.

Related: A Git LFS [data pack](https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/upgrading-git-large-file-storage) to host the [TLA+ video lecture](https://lamport.azurewebsites.net/video/videos.html) videos is currently charged to my corporate credit card.

**Comment by lemmy** [comment]
AWS has accepted the TLA+ Foundation into their Open Source Credits Program, granting us a budget to reinstate continuous performance tests. @Calvin-L and @fhackett, please let me know if you'd like to revive the performance tests as part of https://github.com/tlaplus/tlaplus/pull/1079.

**Comment by lemmy** [comment]
The old performance tests were quite straightforward. An Equinix-sponsored machine was always on and connected to our [GitHub automation](https://github.com/tlaplus/tlaplus/blob/master/.github/workflows/perf.yml) as a [“self-hosted” runner](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners). Our AWS budget is insufficient to maintain an always-on machine, which is why we haev to figure out how to start and stop the instance as part of our GitHub automation.

**Comment by fhackett** [comment]
@lemmy thinking about the start/stop issue, maybe a good way is to have a non-hosted action that starts the machine, sends data to it, launches the benchmark, and then shuts down the machine at the end.

I built something like that for some Azure machines before, though the context was a little different and only one person was expected to use it at a time.

The main weakness is the possibility that the machine stays on due to a bug, and concurrency management for multiple benchmark runs (including strange behavior like sending shutdown during a running benchmark accidentally).

**Comment by lemmy** [comment]
If AWS credentials can somehow be securely stored in workflow secrets, executing `aws ec2 run-instances …` followed by a busy wait at the beginning of the file `https://github.com/tlaplus/tlaplus/blob/master/.github/workflows/perf.yml` should suffice.

**Comment by fhackett** [comment]
Assuming AWS operates with tokens like Azure and Cloudflare do, then I am reasonably certain that principle would work (I just recently did something like this for Cloudflare wrangler ops).

I wonder, though, whether different steps of an action can run on different runners. It seems `runs-on` is for the whole workflow and not part of it, so it may be tricky to switch from default Github Actions runner calling `aws ec2 run-instances...` to the runner that was just started.

Even if that's the case, it could still be possible to replace most of the steps with `scp` for the artifacts and then launching a remote script that runs the benchmark with SSH. If we constrain one instance of that action to run at a time (I think that's a toggle), then the action flow could be (assuming Github-enforced exclusivity):
- start machine using AWS credentials, get the machine's SSH key (used in next 2 steps)
- fetch artifacts using Github infra, scp them onto the machine
- run the benchmarking script
- extract benchmarking artifacts with scp, store them in Github
- stop machine

Or maybe you can just specify which machine to use per step, and none of this matters. I haven't seen anything like that in my reading of docs so far though.

**Comment by lemmy** [comment]
https://github.com/machulav/ec2-github-runner with a "vanilla EC2 AMI" seems to do what we want.

**Comment by lemmy** [comment]
https://github.com/runs-on/runs-on is another contender.

An interesting change could be to divide our sequential performance benchmarks into concurrent benchmarks running on AWS spot instances. With performance benchmarks, it seems acceptable to wait a certain period for a spot instances to become available.  Short-lived benchmarks are a better fit for spot instances.  https://github.com/runs-on/runs-on supports spot instances while https://github.com/machulav/ec2-github-runner has a [PR open](https://github.com/machulav/ec2-github-runner/pull/171).

**Comment by lemmy** [comment]
At a first glance, https://aws.amazon.com/ec2/instance-types/r7iz/ or https://aws.amazon.com/ec2/instance-types/r7i/ with eight vCPUs (why vCPU if it is bare metal?) seem to be a good fit for our workload.

**Comment by fhackett** [comment]
Interesting - both those options seem much simpler than my hand-coded idea. I didn't think to look up "elastic" runners - just somehow assumed it wouldn't exist.

I'll try to form some sort of opinion re: machine types etc, but this seems like a more plausible direction already.

**Comment by fhackett** [comment]
I did some investigating of AWS EC2 offerings, and I have 2 thoughts:
- for questions like r7iz vs r7i, I don't think it matters. Both offerings differ in terms of advanced features a benchmark (which is bottlenecked exclusively by CPU / RAM / disk) does not need, so I would just pick the cheapest one with acceptable relevant parameters. We also don't need strictly the fastest hardware, just a consistent measure of a "good workstation" (because that's what our users will be using mostly), as long as it can handle all the benchmark executions.
- I originally thought vCPUs was a notation thing, but it seems maybe only `.metal` instances are real hardware, and everything else is a VM? Seems implied from this article, when I tried looking up what the `.metal` identifier means https://aws.amazon.com/blogs/aws/new-amazon-ec2-bare-metal-instances-with-direct-access-to-hardware/. If true, this suggests that we might want a lower spec `.metal` system for stability of measurements. After scrolling around a bit, the lowest spec "full machine" I could find was something like `m5zn.metal`, which is still complete overkill in CPU count but has _only_ 192 GB of memory. Makes sense that it's hard to find a "normal" spec bare metal machine though, because Amazon would make so much more money buying giant servers and slicing them up, rather than waste rack space on lower density gear.
  I also have no idea about the cost effectiveness of a choice like this. I know neither our exact budget, nor did I check the expected numbers.

Thoughts? I'm just reading here and there, so everything I just wrote is an educated guess.

Also, maybe the distinction between VM and true bare metal is not important (you could convince me it's fine to run on a VM as long as we're consistent), but I figure it's worth understanding what we're asking AWS for at minimum.

**Comment by lemmy** [comment]
I initially chose a bare-metal instance to shield the performance benchmarks from noisy neighbors, which are those virtual machine neighbors who exhaust their allocated resources. Can you calculate the number of hours we can get with a budget of say $4000? If this gives us approximately 8 hours a week on a bare-metal instance, I would be inclined to go with that option.

**Comment by fhackett** [comment]
@lemmy is that monthly or yearly?

The AWS tools operate in monthly prices, and if that number is a monthly budget then several options might work.
If it's yearly, then I'll have to look closer (and multiply all the estimates by 12).

Strangely, according to the price calculator, in some cases "weekly spike traffic" (the way I tried to input 8hrs per week) is actually more expensive than constant usage with a yearly savings plan... not entirely sure what that implies yet.

**Comment by lemmy** [comment]
$4000 is half of our annual budget.

**Comment by fhackett** [comment]
I see, thanks for clarifying. That means the monthly budget is approximately $333 USD (I double checked and, while I am in Canada, AWS is still quoting me in USD also).

Aside: I figured out what I was doing wrong in the cost calculator. I misread its base + peak usage selection and didn't realize you could claim baseline usage of 0 instances w/ peak of 1 (what we actually want). Before, I was looking at 1 baseline (constant usage), peak of 2.

So, taking that into account, intermittent usage of 8hrs per week at on-demand pricing seems generally best. Spot instances are cheaper (about 60%), but it's already so much less than your effective monthly budget of $333 that it might not be worth the potential inconvenience. The smallest `.metal` type is `c6g.metal`, which is predicted to cost $75.64 / month at the expected usage level. That's 64 CPU cores and 128GB of memory, all bare metal. Storage is configurable and seems to add in the region of <$1 depending on setup.

From my understanding, this is basically overkill in hardware specs even with the smallest possible .metal instance. You could probably run the state queue and the whole runner on a RAM disk at that point and store nothing beyond the most basic OS image.

That's my thought, now I know some more information. Let me know what you think.

**Comment by lemmy** [comment]
The linked run at https://github.com/tlaplus/tlaplus/actions/runs/12815549865/job/35734450528 was executed using the [`runs-on`](https://github.com/runs-on/runs-on) project, utilizing an EC2 `c7gd.4xlarge` instance (`aarch64` architecture) and running `Ubuntu 22`. This instance type comes with a local NVMe disk with sufficient storage capacity: 

https://github.com/tlaplus/tlaplus/blob/cca02d0d70fc5c514e47feb2af04a933d86a6a25/.github/workflows/perf.yml#L14-L17

Kudos to @crohr because setting up `runs-on` was remarkably simple and straightforward!

**Comment by crohr** [comment]
@lemmy that’s awesome great that you find it useful!

**Comment by fhackett** [comment]
@lemmy Looks like the benchmarks work now; results seem usable. I'm not sure where this goes from here, though.

Should we evaluate #1079  using that setup? (I don't have the controls to do any of that directly myself)
