### ISSUE TITLE
Unify version of Java targeted by the tools

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#921]
Currently our Java version story is a bit out of focus:

- In the `compile` target of the ant build, the `source` and `target` are set to `1.8`, aka Java 8
- We use the `jdk.jfr` API, which became public in Java 9; however we are using the Java 11 version (which causes build issues on windows, see #914)
- In the CI we specify Java 11 (ref #920)

So is it just Java 11 then? We should switch to specifying the `release="11"` parameter to the ant `javac` task instead of the `source` and `target` parameters? Because currently we are declaring that the tools are compatible with Java 8 which is not true and produces the "bootstrap class path not set in conjunction with -source 8" warning during compilation.

**Comment by lemmy** [comment]
Parts a tla2tools.jar should still work with Java 1.8.

**Comment by ahelwer** [comment]
If an execution does not use the `TLAFlightRecorder` class then yes it will work with Java 8. However I don't think it's a good idea to ship a library that says it's Java 8 compatible while parts of it are not Java 8 compatible and will fail at runtime for that reason.

**Comment by lemmy** [comment]
Users can put their own version of `TLAFlightRecorder` on the classpath and continue with 1.8.  IIRC there are still users with 1.8 out there.

**Comment by ahelwer** [comment]
All right well an issue is we won't be able to add `-Werror` to the javac args to treat warnings as errors (thus keeping more from being added) because javac detects that the code it's compiling isn't v8-compatible and issues the bootstrap path warning. Also it won't compile on Windows which is more strict about this kind of thing I guess.

**Comment by lemmy** [comment]
Can you explain why Java is more strict on Windows?  This sounds strange given that Java's main feature is platform independence.

**Comment by ahelwer** [comment]
Well it's a compile-once-run-anywhere thing so any artifacts we compile will run on windows just fine, but the actual act of compilation is I guess different enough that actually trying to run the ant build on windows will fail with "unable to find jdk.jfr package" errors. Maybe there's a workaround but I wasn't able to find it other than specifying `release="11"` in the customBuild.xml file.

**Comment by lemmy** [comment]
This must be a local issue because compilation on Windows used to work when the CI (including UI tests) still ran on Azure Pipelines.  At any rate, let's make a conscious/explicit decision to break (partial) 1.8 compatibly, instead of as a side-effect of turning warnings into errors.  A message to the TLA+ Google group could, perhaps, answer if some users are still on 1.8.

**Comment by ahelwer** [comment]
I posted here: https://groups.google.com/g/tlaplus/c/BReLjG8ako4

If we go through with this change I suggest bumping the minor version so nightly releases are uploaded to a separate release from where they're uploaded now.

**Comment by Calvin-L** [comment]
> I don't think it's a good idea to ship a library that says it's Java 8 compatible while parts of it are not Java 8 compatible and will fail at runtime for that reason.

Welcome to the Java Ecosystem! 😅 What you've described is not a _best_ practice, but it is _a_ practice, and a remarkably common one.

Since AFAIK there's no flag or environment variable to disable `TLAFlightRecorder`, here's what I think we should do ---

> IIRC there are still users with 1.8 out there.

The right (?) way to support those users is to ship a [multi-release jar](https://docs.oracle.com/en/java/javase/21/docs/specs/jar/jar.html#multi-release-jar-files):
 - Most of the tools' source code (including a no-op implementation of `TLAFlightRecorder`) should be compiled with `-release 8` as @ahelwer suggested.
 - The real implementation of `TLAFlightRecorder` compiled with `-release 9` should be placed in the `META-INF/versions/9` subdirectory of the final jar.
 - The final jar manifest should include `Multi-Release: true`.

**Comment by lemmy** [comment]
It should be confirmed that OSGi (the Toolbox) correctly handles such a multi-release.jar.  That said, https://metabase.tlapl.us/dashboard/1 does not indicate Java 8 users.

**Comment by Calvin-L** [comment]
[Recent versions of OSGi do support multi-release jars](https://blog.osgi.org/2018/02/osgi-r7-highlights-java-9-support.html), but the toolbox might be using an older version that doesn't. (I don't know enough about OSGi to tell.)

If dropping Java 8 support is an option, it seems like the best one. I won't miss it. :)

**Comment by lemmy** [comment]
Mention it one more time at next week's community meeting?
